// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { UikTikRelation } from "../protocol/types";

export const duma_2007_uik_to_tik_region_85 = [
  {
    "uikNumber": 1,
    "uikTvd": "4854001101323",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 2,
    "uikTvd": "4854001101324",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 3,
    "uikTvd": "4854001101325",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 4,
    "uikTvd": "4854001101326",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 5,
    "uikTvd": "4854001101327",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 6,
    "uikTvd": "4854001101328",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 7,
    "uikTvd": "4854001101329",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 8,
    "uikTvd": "4854001101330",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 9,
    "uikTvd": "4854001101331",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 10,
    "uikTvd": "4854001101332",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 11,
    "uikTvd": "4854001101333",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 12,
    "uikTvd": "4854001101334",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 13,
    "uikTvd": "4854001101335",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 14,
    "uikTvd": "4854001101336",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 15,
    "uikTvd": "4854001101337",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 16,
    "uikTvd": "4854001101338",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 17,
    "uikTvd": "4854001101339",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 18,
    "uikTvd": "4854001101340",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 19,
    "uikTvd": "4854001101341",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 20,
    "uikTvd": "4854001101342",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 21,
    "uikTvd": "4854001101343",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 22,
    "uikTvd": "4854001101344",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 23,
    "uikTvd": "4854001101345",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 24,
    "uikTvd": "4854001101346",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 25,
    "uikTvd": "4854001101347",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 26,
    "uikTvd": "4854001101348",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 27,
    "uikTvd": "4854001101349",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 28,
    "uikTvd": "4854001101350",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 29,
    "uikTvd": "4854001101351",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 30,
    "uikTvd": "4854001101352",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 31,
    "uikTvd": "4854001101353",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 32,
    "uikTvd": "4854001101354",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 33,
    "uikTvd": "4854001101355",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 34,
    "uikTvd": "4854001101356",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 35,
    "uikTvd": "4854001101357",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 36,
    "uikTvd": "4854001101358",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 37,
    "uikTvd": "4854001101359",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 38,
    "uikTvd": "4854001101360",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 39,
    "uikTvd": "4854001101361",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 40,
    "uikTvd": "4854001101362",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 41,
    "uikTvd": "4854001101363",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 42,
    "uikTvd": "4854001101364",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 43,
    "uikTvd": "4854001101365",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 44,
    "uikTvd": "4854001101366",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 45,
    "uikTvd": "4854001101367",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 46,
    "uikTvd": "4854001101368",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 47,
    "uikTvd": "4854001101369",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 48,
    "uikTvd": "4854001101370",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  },
  {
    "uikNumber": 49,
    "uikTvd": "485400291375",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 50,
    "uikTvd": "485400291376",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 51,
    "uikTvd": "485400291377",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 52,
    "uikTvd": "485400291378",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 53,
    "uikTvd": "485400291379",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 54,
    "uikTvd": "485400291380",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 55,
    "uikTvd": "485400291381",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 56,
    "uikTvd": "485400291382",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 57,
    "uikTvd": "485400291383",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 58,
    "uikTvd": "485400291384",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 59,
    "uikTvd": "485400291385",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 60,
    "uikTvd": "485400291386",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 61,
    "uikTvd": "485400291387",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 62,
    "uikTvd": "485400291388",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 63,
    "uikTvd": "485400291389",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 64,
    "uikTvd": "485400291390",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 65,
    "uikTvd": "485400291391",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 66,
    "uikTvd": "485400291392",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 67,
    "uikTvd": "485400291393",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 68,
    "uikTvd": "485400291394",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 69,
    "uikTvd": "485400291395",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 70,
    "uikTvd": "485400291396",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 71,
    "uikTvd": "485400291397",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 72,
    "uikTvd": "485400291398",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 73,
    "uikTvd": "485400291399",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 74,
    "uikTvd": "485400291400",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 75,
    "uikTvd": "485400291401",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 76,
    "uikTvd": "485400291402",
    "tikTvd": "2852000101159",
    "tikName": "Баяндаевская"
  },
  {
    "uikNumber": 77,
    "uikTvd": "4854003102111",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 78,
    "uikTvd": "4854003102112",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 79,
    "uikTvd": "4854003102113",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 80,
    "uikTvd": "4854003102114",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 81,
    "uikTvd": "4854003102115",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 82,
    "uikTvd": "4854003102116",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 83,
    "uikTvd": "4854003102117",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 84,
    "uikTvd": "4854003102118",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 85,
    "uikTvd": "4854003102119",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 86,
    "uikTvd": "4854003102120",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 87,
    "uikTvd": "4854003102121",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 88,
    "uikTvd": "4854003102122",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 89,
    "uikTvd": "4854003102123",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 90,
    "uikTvd": "4854003102124",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 91,
    "uikTvd": "4854003102125",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 92,
    "uikTvd": "4854003102126",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 93,
    "uikTvd": "4854003102127",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 94,
    "uikTvd": "4854003102128",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 95,
    "uikTvd": "4854003102129",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 96,
    "uikTvd": "4854003102130",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 97,
    "uikTvd": "4854003102131",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 98,
    "uikTvd": "4854003102132",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 99,
    "uikTvd": "4854003102133",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 100,
    "uikTvd": "4854003102134",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 101,
    "uikTvd": "4854003102135",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 102,
    "uikTvd": "4854003102136",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 103,
    "uikTvd": "4854003102137",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 104,
    "uikTvd": "4854003102138",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 105,
    "uikTvd": "4854003102139",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 106,
    "uikTvd": "4854003102140",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 107,
    "uikTvd": "4854003102141",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 108,
    "uikTvd": "4854003102142",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 109,
    "uikTvd": "4854003102143",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 110,
    "uikTvd": "4854003102144",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 111,
    "uikTvd": "4854003102145",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 112,
    "uikTvd": "4854003102146",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 113,
    "uikTvd": "4854003102147",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 114,
    "uikTvd": "4854003102275",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 115,
    "uikTvd": "4854003102276",
    "tikTvd": "2852000101160",
    "tikName": "Боханская"
  },
  {
    "uikNumber": 116,
    "uikTvd": "485400487707",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 117,
    "uikTvd": "485400487708",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 118,
    "uikTvd": "485400487709",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 119,
    "uikTvd": "485400487710",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 120,
    "uikTvd": "485400487711",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 121,
    "uikTvd": "485400487712",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 122,
    "uikTvd": "485400487713",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 123,
    "uikTvd": "485400487714",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 124,
    "uikTvd": "485400487715",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 125,
    "uikTvd": "485400487716",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 126,
    "uikTvd": "485400487717",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 127,
    "uikTvd": "485400487718",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 128,
    "uikTvd": "485400487719",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 129,
    "uikTvd": "485400487720",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 130,
    "uikTvd": "485400487721",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 131,
    "uikTvd": "485400487722",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 132,
    "uikTvd": "485400487723",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 133,
    "uikTvd": "485400487724",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 134,
    "uikTvd": "485400487725",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 135,
    "uikTvd": "485400487726",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 136,
    "uikTvd": "485400487727",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 137,
    "uikTvd": "485400487728",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 138,
    "uikTvd": "485400487729",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 139,
    "uikTvd": "485400487730",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 140,
    "uikTvd": "485400487731",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 141,
    "uikTvd": "485400487732",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 142,
    "uikTvd": "485400487733",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 143,
    "uikTvd": "485400487734",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 144,
    "uikTvd": "485400487735",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 145,
    "uikTvd": "485400487736",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 146,
    "uikTvd": "485400487737",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 147,
    "uikTvd": "485400487738",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 148,
    "uikTvd": "485400487739",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 149,
    "uikTvd": "485400487740",
    "tikTvd": "2852000101161",
    "tikName": "Нукутская"
  },
  {
    "uikNumber": 150,
    "uikTvd": "485400592110",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 151,
    "uikTvd": "485400592111",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 152,
    "uikTvd": "485400592112",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 153,
    "uikTvd": "485400592113",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 154,
    "uikTvd": "485400592114",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 155,
    "uikTvd": "485400592115",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 156,
    "uikTvd": "485400592116",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 157,
    "uikTvd": "485400592117",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 158,
    "uikTvd": "485400592118",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 159,
    "uikTvd": "485400592119",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 160,
    "uikTvd": "485400592120",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 161,
    "uikTvd": "485400592121",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 162,
    "uikTvd": "485400592122",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 163,
    "uikTvd": "485400592123",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 164,
    "uikTvd": "485400592124",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 165,
    "uikTvd": "485400592125",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 166,
    "uikTvd": "485400592126",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 167,
    "uikTvd": "485400592127",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 168,
    "uikTvd": "485400592128",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 169,
    "uikTvd": "485400592129",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 170,
    "uikTvd": "485400592130",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 171,
    "uikTvd": "485400592131",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 172,
    "uikTvd": "485400592132",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 173,
    "uikTvd": "485400592133",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 174,
    "uikTvd": "485400592134",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 175,
    "uikTvd": "485400592135",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 176,
    "uikTvd": "485400592136",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 177,
    "uikTvd": "485400592137",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 178,
    "uikTvd": "485400592138",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 179,
    "uikTvd": "485400592139",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 180,
    "uikTvd": "485400592140",
    "tikTvd": "2852000101162",
    "tikName": "Осинская"
  },
  {
    "uikNumber": 181,
    "uikTvd": "485400698252",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 182,
    "uikTvd": "485400698253",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 183,
    "uikTvd": "485400698254",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 184,
    "uikTvd": "485400698255",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 185,
    "uikTvd": "485400698256",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 186,
    "uikTvd": "485400698257",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 187,
    "uikTvd": "485400698258",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 188,
    "uikTvd": "485400698259",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 189,
    "uikTvd": "485400698260",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 190,
    "uikTvd": "485400698261",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 191,
    "uikTvd": "485400698262",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 192,
    "uikTvd": "485400698263",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 193,
    "uikTvd": "485400698264",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 194,
    "uikTvd": "485400698265",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 195,
    "uikTvd": "485400698266",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 196,
    "uikTvd": "485400698267",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 197,
    "uikTvd": "485400698268",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 198,
    "uikTvd": "485400698269",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 199,
    "uikTvd": "485400698270",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 200,
    "uikTvd": "485400698271",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 201,
    "uikTvd": "485400698272",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 202,
    "uikTvd": "485400698273",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 203,
    "uikTvd": "485400698274",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 204,
    "uikTvd": "485400698275",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 205,
    "uikTvd": "485400698276",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 206,
    "uikTvd": "485400698277",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 207,
    "uikTvd": "485400698278",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 208,
    "uikTvd": "485400698279",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 209,
    "uikTvd": "485400698280",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 210,
    "uikTvd": "485400698281",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 211,
    "uikTvd": "485400698282",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 212,
    "uikTvd": "485400698283",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 213,
    "uikTvd": "485400698284",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 214,
    "uikTvd": "485400698285",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 215,
    "uikTvd": "485400698286",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 216,
    "uikTvd": "485400698287",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 217,
    "uikTvd": "485400698288",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 218,
    "uikTvd": "485400698289",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 219,
    "uikTvd": "485400698290",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 220,
    "uikTvd": "485400698291",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 221,
    "uikTvd": "485400698292",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 222,
    "uikTvd": "485400698293",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 223,
    "uikTvd": "485400698294",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 224,
    "uikTvd": "485400698295",
    "tikTvd": "2852000101163",
    "tikName": "Эхирит-Булагатская"
  },
  {
    "uikNumber": 225,
    "uikTvd": "4854001101371",
    "tikTvd": "2852000101158",
    "tikName": "Аларская"
  }
] satisfies readonly UikTikRelation[];
