// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2003_districts_region_9 = [
  {
    "election": "2003-duma",
    "districtNumber": 16,
    "oikTvd": "100100095806",
    "oikName": "Карачаево-Черкесский",
    "regionCode": "9",
    "regionTvd": "100100095805",
    "regionName": "Карачаево-Черкесская Республика",
    "winnerCandidateVibid": "1001000225877",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:1001000201796",
        "candidateVibid": "1001000201796",
        "fullName": "Коджаков Олег Юнусович",
        "nominatingEntity": "\"Великая Россия - Евразийский Союз\"",
        "registrationStatus": "114 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000212548",
        "candidateVibid": "1001000212548",
        "fullName": "Шрамко Евгений Александрович",
        "nominatingEntity": "\"Демократическая партия России\"",
        "registrationStatus": "123 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000121791",
        "candidateVibid": "1001000121791",
        "fullName": "Михайлович Муратхан Аджигереевна",
        "nominatingEntity": "\"Коммунистическая партия Российской Федерации (КПРФ)\"",
        "registrationStatus": "104 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000131374",
        "candidateVibid": "1001000131374",
        "fullName": "Текеев Алимурат Абюсупович",
        "nominatingEntity": "\"НАРОДНАЯ ПАРТИЯ Российской Федерации\"",
        "registrationStatus": "115 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000254180",
        "candidateVibid": "1001000254180",
        "fullName": "Гудимов Андрей Юрьевич",
        "nominatingEntity": "\"Народно-республиканская партия России\"",
        "registrationStatus": "125 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000195024",
        "candidateVibid": "1001000195024",
        "fullName": "Богданов Анатолий Александрович",
        "nominatingEntity": "\"Объединенная Российская партия \"Русь\"",
        "registrationStatus": "120 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000225877",
        "candidateVibid": "1001000225877",
        "fullName": "Максимова Надежда Сергеевна",
        "nominatingEntity": "\"Политическая партия \"Единая Россия\"",
        "registrationStatus": "депутат",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:1001000220802",
        "candidateVibid": "1001000220802",
        "fullName": "Ферисов Федор Кузьмич",
        "nominatingEntity": "\"РОССИЙСКАЯ ПАРТИЯ ПЕНСИОНЕРОВ И ПАРТИЯ СОЦИАЛЬНОЙ СПРАВЕДЛИВОСТИ\"",
        "registrationStatus": "122 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000187984",
        "candidateVibid": "1001000187984",
        "fullName": "Джоган Фатима Магометовна",
        "nominatingEntity": "\"Родина\" (народно-патриотический союз)\"",
        "registrationStatus": "119 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000113895",
        "candidateVibid": "1001000113895",
        "fullName": "Хабичева Асият Ахияевна",
        "nominatingEntity": "\"СОЮЗ ПРАВЫХ СИЛ\"",
        "registrationStatus": "103 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070642",
        "candidateVibid": "209200070642",
        "fullName": "Акбаев Азрет Алиевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "102 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070783",
        "candidateVibid": "209200070783",
        "fullName": "Байрамкулов Халит Салыхович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "124 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070653",
        "candidateVibid": "209200070653",
        "fullName": "Батчаев Борис Сафарович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "101 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070392",
        "candidateVibid": "209200070392",
        "fullName": "Боташев Осман Хадши-Махмутович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "100 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070467",
        "candidateVibid": "209200070467",
        "fullName": "Горин Александр Федорович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "99 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070882",
        "candidateVibid": "209200070882",
        "fullName": "Гринько Владимир Александрович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "126 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070912",
        "candidateVibid": "209200070912",
        "fullName": "Джегутанова Загират Рамазановна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "106 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070835",
        "candidateVibid": "209200070835",
        "fullName": "Джукаев Азрет-Али Наштукаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "112 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070889",
        "candidateVibid": "209200070889",
        "fullName": "Катчиев Ахмат Абдулович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "выбывший после регистрации кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070960",
        "candidateVibid": "209200070960",
        "fullName": "Мостовой Петр Петрович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "выбывший после регистрации кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070774",
        "candidateVibid": "209200070774",
        "fullName": "Скориков Виктор Александрович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "113 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070768",
        "candidateVibid": "209200070768",
        "fullName": "Текеев Магомет Абдул-Халимович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "110 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070808",
        "candidateVibid": "209200070808",
        "fullName": "Тимофеев Игорь Эдуардович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "107 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070695",
        "candidateVibid": "209200070695",
        "fullName": "Тоторкулов Шагабан Муссаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "108 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:209200070859",
        "candidateVibid": "209200070859",
        "fullName": "Хубиев Сагит Азаматович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "108 зарегистрированный кандидат",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "sha256": "3cb3847158e549e1508e667a587e5200fc13063a4e97f29315f465bad115fcc6",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:33.968606+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/karachaev-cherkess?action=show&root=1000185&tvd=100100095806&vrn=100100095619&region=9&global=null&sub_region=9&prver=0&pronetvd=null&type=223",
        "sha256": "40f45912a1335eb5992345a6787367e0cbd7b71fd06aeebabfbab4c4d4206c08",
        "retrievedAt": "2026-08-28T07:41:36.946549+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/karachaev-cherkess?action=show&root=1000185&tvd=100100095806&vrn=100100095619&region=9&global=null&sub_region=9&prver=0&pronetvd=null&type=223",
        "provenance": "live-official",
        "sourceReportType": 223,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 82529,
        "summedTikWinnerVoteTotal": 82529
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
