// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2003_districts_region_79 = [
  {
    "election": "2003-duma",
    "districtNumber": 214,
    "oikTvd": "100100095796",
    "oikName": "Биробиджанский",
    "regionCode": "79",
    "regionTvd": "100100095795",
    "regionName": "Еврейская автономная область",
    "winnerCandidateVibid": "1001000121950",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:1001000121950",
        "candidateVibid": "1001000121950",
        "fullName": "Штогрин Сергей Иванович",
        "nominatingEntity": "\"Коммунистическая партия Российской Федерации (КПРФ)\"",
        "registrationStatus": "депутат",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:1001000136168",
        "candidateVibid": "1001000136168",
        "fullName": "Амелин Артур Владимирович",
        "nominatingEntity": "\"ЛДПР\"",
        "registrationStatus": "5/16 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000226021",
        "candidateVibid": "1001000226021",
        "fullName": "Виноградов Андрей Павлович",
        "nominatingEntity": "\"Политическая партия \"Единая Россия\"",
        "registrationStatus": "5/18 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000220856",
        "candidateVibid": "1001000220856",
        "fullName": "Гуменный Алексей Маркович",
        "nominatingEntity": "\"РОССИЙСКАЯ ПАРТИЯ ПЕНСИОНЕРОВ И ПАРТИЯ СОЦИАЛЬНОЙ СПРАВЕДЛИВОСТИ\"",
        "registrationStatus": "утративший статус выдв. кандидата",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000112288",
        "candidateVibid": "1001000112288",
        "fullName": "Хомченко Алексей Владиславович",
        "nominatingEntity": "\"Российская демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "3/12 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:279200066952",
        "candidateVibid": "279200066952",
        "fullName": "Максимов Анатолий Викторович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "6/23 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:279200066704",
        "candidateVibid": "279200066704",
        "fullName": "Назаров Василий Сергеевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "6/24 кандидат с отказом в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:279200066907",
        "candidateVibid": "279200066907",
        "fullName": "Шиманович Евгений Борисович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "6/22 зарегистрированный кандидат",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "sha256": "3cb3847158e549e1508e667a587e5200fc13063a4e97f29315f465bad115fcc6",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:33.968606+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/jewish-aut?action=show&root=1000175&tvd=100100095796&vrn=100100095619&region=79&global=null&sub_region=79&prver=0&pronetvd=null&type=223",
        "sha256": "982933657e798278c1556b79dd33fece3d02af39bd9072a11ac6dbd9339cb335",
        "retrievedAt": "2026-08-28T07:42:03.208379+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/jewish-aut?action=show&root=1000175&tvd=100100095796&vrn=100100095619&region=79&global=null&sub_region=79&prver=0&pronetvd=null&type=223",
        "provenance": "live-official",
        "sourceReportType": 223,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 37203,
        "summedTikWinnerVoteTotal": 37203
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
