// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2003_districts_region_33 = [
  {
    "election": "2003-duma",
    "districtNumber": 68,
    "oikTvd": "100100095653",
    "oikName": "Владимирский",
    "regionCode": "33",
    "regionTvd": "100100095652",
    "regionName": "Владимирская область",
    "winnerCandidateVibid": "1001000121837",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:1001000217917",
        "candidateVibid": "1001000217917",
        "fullName": "Чуркин Геннадий Иванович",
        "nominatingEntity": "\"Аграрная партия России\"",
        "registrationStatus": "66 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000202297",
        "candidateVibid": "1001000202297",
        "fullName": "Андрианов Николай Ефимович",
        "nominatingEntity": "\"Великая Россия - Евразийский Союз\"",
        "registrationStatus": "71 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000203753",
        "candidateVibid": "1001000203753",
        "fullName": "Варнавский Александр Егорович",
        "nominatingEntity": "\"ЕДИНЕНИЕ\"",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000121837",
        "candidateVibid": "1001000121837",
        "fullName": "Игошин Игорь Николаевич",
        "nominatingEntity": "\"Коммунистическая партия Российской Федерации (КПРФ)\"",
        "registrationStatus": "депутат",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:1001000260885",
        "candidateVibid": "1001000260885",
        "fullName": "Смирнов Аркадий Аркадьевич",
        "nominatingEntity": "\"Консервативная партия России\"",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000136041",
        "candidateVibid": "1001000136041",
        "fullName": "Малаховский Семен Павлович",
        "nominatingEntity": "\"ЛДПР\"",
        "registrationStatus": "72 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000190333",
        "candidateVibid": "1001000190333",
        "fullName": "Есякова Галина Викторовна",
        "nominatingEntity": "\"Партия Возрождения России - Российская партия ЖИЗНИ\"",
        "registrationStatus": "68 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000126400",
        "candidateVibid": "1001000126400",
        "fullName": "Шибаршин Игорь Алексеевич",
        "nominatingEntity": "\"Партия Мира и Единства (ПМЕ)\"",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000220815",
        "candidateVibid": "1001000220815",
        "fullName": "Леонтьев Александр Геннадьевич",
        "nominatingEntity": "\"РОССИЙСКАЯ ПАРТИЯ ПЕНСИОНЕРОВ И ПАРТИЯ СОЦИАЛЬНОЙ СПРАВЕДЛИВОСТИ\"",
        "registrationStatus": "69 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000113922",
        "candidateVibid": "1001000113922",
        "fullName": "Казаков Сергей Валентинович",
        "nominatingEntity": "\"СОЮЗ ПРАВЫХ СИЛ\"",
        "registrationStatus": "61 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300170781",
        "candidateVibid": "333300170781",
        "fullName": "Артемов Игорь Владимирович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "60 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300171576",
        "candidateVibid": "333300171576",
        "fullName": "Беляков Антон Владимирович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "74 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300171500",
        "candidateVibid": "333300171500",
        "fullName": "Волков Анатолий Алексеевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "73 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300171573",
        "candidateVibid": "333300171573",
        "fullName": "Давыдкин Юрий Николаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300170778",
        "candidateVibid": "333300170778",
        "fullName": "Дулов Сергей Юльевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "81 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300170905",
        "candidateVibid": "333300170905",
        "fullName": "Зоткин Михаил Васильевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300170860",
        "candidateVibid": "333300170860",
        "fullName": "Ивашкевич Анатолий Павлович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "80 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300171570",
        "candidateVibid": "333300171570",
        "fullName": "Саркисов Сергей Эдуардович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300170955",
        "candidateVibid": "333300170955",
        "fullName": "Шикунов Александр Дмитриевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "67 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300170877",
        "candidateVibid": "333300170877",
        "fullName": "Шохин Андрей Станиславович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "выбывший после регистрации кандидат",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "sha256": "3cb3847158e549e1508e667a587e5200fc13063a4e97f29315f465bad115fcc6",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:33.968606+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/vladimir?action=show&root=1000032&tvd=100100095653&vrn=100100095619&region=33&global=null&sub_region=33&prver=0&pronetvd=null&type=223",
        "sha256": "47b6e002d2410190cbb7145f0b24c58712e2f4b2379ea1d46a496d771c046021",
        "retrievedAt": "2026-08-28T07:41:43.014754+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/vladimir?action=show&root=1000032&tvd=100100095653&vrn=100100095619&region=33&global=null&sub_region=33&prver=0&pronetvd=null&type=223",
        "provenance": "live-official",
        "sourceReportType": 223,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 65137,
        "summedTikWinnerVoteTotal": 65137
      }
    }
  },
  {
    "election": "2003-duma",
    "districtNumber": 69,
    "oikTvd": "100100095654",
    "oikName": "Ковровский",
    "regionCode": "33",
    "regionTvd": "100100095652",
    "regionName": "Владимирская область",
    "winnerCandidateVibid": "333300270371",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:1001000202298",
        "candidateVibid": "1001000202298",
        "fullName": "Шубников Игорь Павлович",
        "nominatingEntity": "\"Великая Россия - Евразийский Союз\"",
        "registrationStatus": "39 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000203754",
        "candidateVibid": "1001000203754",
        "fullName": "Ковезин Алексей Анатольевич",
        "nominatingEntity": "\"ЕДИНЕНИЕ\"",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000260886",
        "candidateVibid": "1001000260886",
        "fullName": "Буянов Михаил Анатольевич",
        "nominatingEntity": "\"Консервативная партия России\"",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000136042",
        "candidateVibid": "1001000136042",
        "fullName": "Бодров Дмитрий Алексеевич",
        "nominatingEntity": "\"ЛДПР\"",
        "registrationStatus": "40 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000190335",
        "candidateVibid": "1001000190335",
        "fullName": "Мельков Вадим Алексеевич",
        "nominatingEntity": "\"Партия Возрождения России - Российская партия ЖИЗНИ\"",
        "registrationStatus": "31 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000126401",
        "candidateVibid": "1001000126401",
        "fullName": "Шпилевский Георгий Антонович",
        "nominatingEntity": "\"Партия Мира и Единства (ПМЕ)\"",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000225929",
        "candidateVibid": "1001000225929",
        "fullName": "Котров Олег Владимирович",
        "nominatingEntity": "\"Политическая партия \"Единая Россия\"",
        "registrationStatus": "38 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000193910",
        "candidateVibid": "1001000193910",
        "fullName": "Ковалев Кирилл Юрьевич",
        "nominatingEntity": "\"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000113923",
        "candidateVibid": "1001000113923",
        "fullName": "Гусев Анатолий Алексеевич",
        "nominatingEntity": "\"СОЮЗ ПРАВЫХ СИЛ\"",
        "registrationStatus": "30 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300270569",
        "candidateVibid": "333300270569",
        "fullName": "Григорьев Николай Михайлович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300270576",
        "candidateVibid": "333300270576",
        "fullName": "Заморин Олег Константинович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "42 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300270566",
        "candidateVibid": "333300270566",
        "fullName": "Кузин Валерий Алексеевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "44 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300270371",
        "candidateVibid": "333300270371",
        "fullName": "Паутов Виктор Николаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "депутат",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:333300270558",
        "candidateVibid": "333300270558",
        "fullName": "Соколов Владимир Сергеевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300270581",
        "candidateVibid": "333300270581",
        "fullName": "Трифонов Игорь Иванович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "45 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:333300270563",
        "candidateVibid": "333300270563",
        "fullName": "Черторицкая Татьяна Владимировна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "41 зарегистрированный кандидат",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "sha256": "3cb3847158e549e1508e667a587e5200fc13063a4e97f29315f465bad115fcc6",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:33.968606+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/vladimir?action=show&root=1000033&tvd=100100095654&vrn=100100095619&region=33&global=null&sub_region=33&prver=0&pronetvd=null&type=223",
        "sha256": "7fa2114a28edea9763471647f7438f27fd6896855b70c5428b2d2f181d45d667",
        "retrievedAt": "2026-08-28T07:41:43.221051+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/vladimir?action=show&root=1000033&tvd=100100095654&vrn=100100095619&region=33&global=null&sub_region=33&prver=0&pronetvd=null&type=223",
        "provenance": "live-official",
        "sourceReportType": 223,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 96795,
        "summedTikWinnerVoteTotal": 96795
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
