// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2003_districts_region_7 = [
  {
    "election": "2003-duma",
    "districtNumber": 14,
    "oikTvd": "100100095871",
    "oikName": "Кабардино-Балкарский",
    "regionCode": "7",
    "regionTvd": "100100095870",
    "regionName": "Кабардино-Балкарская Республика",
    "winnerCandidateVibid": "1001000225875",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:1001000135995",
        "candidateVibid": "1001000135995",
        "fullName": "Макаров Андрей Николаевич",
        "nominatingEntity": "\"ЛДПР\"",
        "registrationStatus": "52/15-1 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000250167",
        "candidateVibid": "1001000250167",
        "fullName": "Тленкопачев Владислав Сафарбиевич",
        "nominatingEntity": "\"Народно-патриотическая партия России\"",
        "registrationStatus": "утративший статус выдв. кандидата",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000195022",
        "candidateVibid": "1001000195022",
        "fullName": "Кучмезов Хаким Далхатович",
        "nominatingEntity": "\"Объединенная Российская партия \"Русь\"",
        "registrationStatus": "50/13-2 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000190278",
        "candidateVibid": "1001000190278",
        "fullName": "Гаев Аслан Далхатович",
        "nominatingEntity": "\"Партия Возрождения России - Российская партия ЖИЗНИ\"",
        "registrationStatus": "51/14-2 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000225875",
        "candidateVibid": "1001000225875",
        "fullName": "Нахушев Заурби Ахмедович",
        "nominatingEntity": "\"Политическая партия \"Единая Россия\"",
        "registrationStatus": "депутат",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:1001000220800",
        "candidateVibid": "1001000220800",
        "fullName": "Атабиев Алий Хакимович",
        "nominatingEntity": "\"РОССИЙСКАЯ ПАРТИЯ ПЕНСИОНЕРОВ И ПАРТИЯ СОЦИАЛЬНОЙ СПРАВЕДЛИВОСТИ\"",
        "registrationStatus": "52/15-2 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000254923",
        "candidateVibid": "1001000254923",
        "fullName": "Дикинов Андзор Хасанбиевич",
        "nominatingEntity": "\"Социал-демократическая партия России\"",
        "registrationStatus": "утративший статус выдв. кандидата",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:207200070990",
        "candidateVibid": "207200070990",
        "fullName": "Тохтабиев Сергей Аминович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "52/15-3 кандидат с отказом в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:207200070757",
        "candidateVibid": "207200070757",
        "fullName": "Шхагошев Адальби Люлевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "51/14-1 зарегистрированный кандидат",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "sha256": "3cb3847158e549e1508e667a587e5200fc13063a4e97f29315f465bad115fcc6",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:33.968606+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/kabardin-balkar?action=show&root=1000250&tvd=100100095871&vrn=100100095619&region=7&global=null&sub_region=7&prver=0&pronetvd=null&type=223",
        "sha256": "1150a2a37a11983170b5d6e176bff28fc5c195769a6006541b2b79ddbf99f995",
        "retrievedAt": "2026-08-28T07:41:36.708874+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/kabardin-balkar?action=show&root=1000250&tvd=100100095871&vrn=100100095619&region=7&global=null&sub_region=7&prver=0&pronetvd=null&type=223",
        "provenance": "live-official",
        "sourceReportType": 223,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 268872,
        "summedTikWinnerVoteTotal": 268872
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
