// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2003_districts_region_49 = [
  {
    "election": "2003-duma",
    "districtNumber": 104,
    "oikTvd": "100100095824",
    "oikName": "Магаданский",
    "regionCode": "49",
    "regionTvd": "100100095823",
    "regionName": "Магаданская область",
    "winnerCandidateVibid": "1001000225952",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:1001000121863",
        "candidateVibid": "1001000121863",
        "fullName": "Давыденко Юрий Борисович",
        "nominatingEntity": "\"Коммунистическая партия Российской Федерации (КПРФ)\"",
        "registrationStatus": "4/19 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000136075",
        "candidateVibid": "1001000136075",
        "fullName": "Гришан Юрий Федорович",
        "nominatingEntity": "\"ЛДПР\"",
        "registrationStatus": "4/20 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000190362",
        "candidateVibid": "1001000190362",
        "fullName": "Багалова Татьяна Константиновна",
        "nominatingEntity": "\"Партия Возрождения России - Российская партия ЖИЗНИ\"",
        "registrationStatus": "4/21 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000225952",
        "candidateVibid": "1001000225952",
        "fullName": "Елисейкин Станислав Агафонович",
        "nominatingEntity": "\"Политическая партия \"Единая Россия\"",
        "registrationStatus": "депутат",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:1001000220821",
        "candidateVibid": "1001000220821",
        "fullName": "Вяльбе Елена Валерьевна",
        "nominatingEntity": "\"РОССИЙСКАЯ ПАРТИЯ ПЕНСИОНЕРОВ И ПАРТИЯ СОЦИАЛЬНОЙ СПРАВЕДЛИВОСТИ\"",
        "registrationStatus": "4/16 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000188009",
        "candidateVibid": "1001000188009",
        "fullName": "Степаненко Нина Захаровна",
        "nominatingEntity": "\"Родина\" (народно-патриотический союз)\"",
        "registrationStatus": "4/23 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000112225",
        "candidateVibid": "1001000112225",
        "fullName": "Тяглов Сергей Николаевич",
        "nominatingEntity": "\"Российская демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "4/15 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:1001000113945",
        "candidateVibid": "1001000113945",
        "fullName": "Сечкин Александр Анатольевич",
        "nominatingEntity": "\"СОЮЗ ПРАВЫХ СИЛ\"",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:249200066914",
        "candidateVibid": "249200066914",
        "fullName": "Буткеев Владимир Анатольевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "4/24 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:249200067038",
        "candidateVibid": "249200067038",
        "fullName": "Каликян Вячеслав Ардавасович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:249200066987",
        "candidateVibid": "249200066987",
        "fullName": "Куркин Олег Николаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:249200067182",
        "candidateVibid": "249200067182",
        "fullName": "Секачева Людмила Леонидовна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "4/25 кандидат с отказом в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:249200067189",
        "candidateVibid": "249200067189",
        "fullName": "Стрельченко Сабина Сергеевна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "4/14 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:249200067216",
        "candidateVibid": "249200067216",
        "fullName": "Ступак Зоя Михайловна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:249200066742",
        "candidateVibid": "249200066742",
        "fullName": "Сулейменов Артур Мухтарович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "4/18 зарегистрированный кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:249200067192",
        "candidateVibid": "249200067192",
        "fullName": "Шестаев Анатолий Трофимович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "4/22 зарегистрированный кандидат",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "sha256": "3cb3847158e549e1508e667a587e5200fc13063a4e97f29315f465bad115fcc6",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:33.968606+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100095621&vrn=100100095619&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100095619&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/magadan?action=show&root=1000203&tvd=100100095824&vrn=100100095619&region=49&global=null&sub_region=49&prver=0&pronetvd=null&type=223",
        "sha256": "0d7c6cde1eb4c3279470490fcb0eccb5ac32126139f5f0a79e2da9447600f80d",
        "retrievedAt": "2026-08-28T07:41:47.724760+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/magadan?action=show&root=1000203&tvd=100100095824&vrn=100100095619&region=49&global=null&sub_region=49&prver=0&pronetvd=null&type=223",
        "provenance": "live-official",
        "sourceReportType": 223,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 26146,
        "summedTikWinnerVoteTotal": 26146
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
