// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { UikTikRelation } from "../protocol/types";

export const duma_2011_uik_to_tik_region_7 = [
  {
    "uikNumber": 1,
    "uikTvd": "407400197760",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 2,
    "uikTvd": "407400197761",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 3,
    "uikTvd": "407400197762",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 4,
    "uikTvd": "407400197763",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 5,
    "uikTvd": "407400197764",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 6,
    "uikTvd": "407400197765",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 7,
    "uikTvd": "407400197766",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 8,
    "uikTvd": "407400197767",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 9,
    "uikTvd": "407400197768",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 10,
    "uikTvd": "407400197769",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 11,
    "uikTvd": "407400197770",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 12,
    "uikTvd": "407400197771",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 13,
    "uikTvd": "407400197772",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 14,
    "uikTvd": "407400197773",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 15,
    "uikTvd": "407400197774",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 16,
    "uikTvd": "407400197775",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 17,
    "uikTvd": "407400197776",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 18,
    "uikTvd": "407400197777",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 19,
    "uikTvd": "407400197778",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 20,
    "uikTvd": "407400197779",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 21,
    "uikTvd": "407400197780",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 22,
    "uikTvd": "407400197781",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 23,
    "uikTvd": "407400197782",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 24,
    "uikTvd": "407400197783",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 25,
    "uikTvd": "407400197784",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 26,
    "uikTvd": "407400197785",
    "tikTvd": "2072000184623",
    "tikName": "Баксанская"
  },
  {
    "uikNumber": 27,
    "uikTvd": "407401292231",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 28,
    "uikTvd": "407401292232",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 29,
    "uikTvd": "407401292233",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 30,
    "uikTvd": "407401292234",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 31,
    "uikTvd": "407401292235",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 32,
    "uikTvd": "407401292236",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 33,
    "uikTvd": "407401292237",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 34,
    "uikTvd": "407401292238",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 35,
    "uikTvd": "407401292239",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 36,
    "uikTvd": "407401292240",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 37,
    "uikTvd": "407401292241",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 38,
    "uikTvd": "407401292242",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 39,
    "uikTvd": "407401292243",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 40,
    "uikTvd": "407401292244",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 41,
    "uikTvd": "407401292245",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 42,
    "uikTvd": "407401292246",
    "tikTvd": "2072000184624",
    "tikName": "Баксанская городская"
  },
  {
    "uikNumber": 43,
    "uikTvd": "407400299671",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 44,
    "uikTvd": "407400299672",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 45,
    "uikTvd": "407400299673",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 46,
    "uikTvd": "407400299674",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 47,
    "uikTvd": "407400299675",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 48,
    "uikTvd": "407400299676",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 49,
    "uikTvd": "407400299677",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 50,
    "uikTvd": "407400299678",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 51,
    "uikTvd": "407400299679",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 52,
    "uikTvd": "407400299680",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 53,
    "uikTvd": "407400299681",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 54,
    "uikTvd": "407400299682",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 55,
    "uikTvd": "407400299683",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 56,
    "uikTvd": "407400299684",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 57,
    "uikTvd": "407400299685",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 58,
    "uikTvd": "407400299686",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 59,
    "uikTvd": "407400299687",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 60,
    "uikTvd": "407400299688",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 61,
    "uikTvd": "407400299689",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 62,
    "uikTvd": "407400299690",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 63,
    "uikTvd": "407400299691",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 64,
    "uikTvd": "407400299692",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 65,
    "uikTvd": "407400299693",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 66,
    "uikTvd": "407400299694",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 67,
    "uikTvd": "407400299695",
    "tikTvd": "2072000184622",
    "tikName": "Зольская"
  },
  {
    "uikNumber": 68,
    "uikTvd": "407401391101",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 69,
    "uikTvd": "407401391102",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 70,
    "uikTvd": "407401391103",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 71,
    "uikTvd": "407401391104",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 72,
    "uikTvd": "407401391105",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 73,
    "uikTvd": "407401391106",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 74,
    "uikTvd": "407401391107",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 75,
    "uikTvd": "407401391108",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 76,
    "uikTvd": "407401391109",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 77,
    "uikTvd": "407401391110",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 78,
    "uikTvd": "407401391111",
    "tikTvd": "2072000184625",
    "tikName": "Лескенская"
  },
  {
    "uikNumber": 79,
    "uikTvd": "407400390492",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 80,
    "uikTvd": "407400390493",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 81,
    "uikTvd": "407400390494",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 82,
    "uikTvd": "407400390495",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 83,
    "uikTvd": "407400390496",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 84,
    "uikTvd": "407400390497",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 85,
    "uikTvd": "407400390498",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 86,
    "uikTvd": "407400390499",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 87,
    "uikTvd": "407400390500",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 88,
    "uikTvd": "407400390501",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 89,
    "uikTvd": "407400390502",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 90,
    "uikTvd": "407400390503",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 91,
    "uikTvd": "407400390504",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 92,
    "uikTvd": "407400390505",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 93,
    "uikTvd": "407400390506",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 94,
    "uikTvd": "407400390507",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 95,
    "uikTvd": "407400390508",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 96,
    "uikTvd": "407400390509",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 97,
    "uikTvd": "407400390510",
    "tikTvd": "2072000184620",
    "tikName": "Майская"
  },
  {
    "uikNumber": 98,
    "uikTvd": "4074004105932",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 99,
    "uikTvd": "4074004105934",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 100,
    "uikTvd": "4074004105935",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 101,
    "uikTvd": "4074004105936",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 102,
    "uikTvd": "4074004105937",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 103,
    "uikTvd": "4074004105938",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 104,
    "uikTvd": "4074004105939",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 105,
    "uikTvd": "4074004105940",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 106,
    "uikTvd": "4074004105942",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 107,
    "uikTvd": "4074004105943",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 108,
    "uikTvd": "4074004105944",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 109,
    "uikTvd": "4074004105945",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 110,
    "uikTvd": "4074004105946",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 111,
    "uikTvd": "4074004105947",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 112,
    "uikTvd": "4074004105948",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 113,
    "uikTvd": "4074004105949",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 114,
    "uikTvd": "4074004105950",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 115,
    "uikTvd": "4074004105951",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 116,
    "uikTvd": "4074004105952",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 117,
    "uikTvd": "4074004105953",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 118,
    "uikTvd": "4074004105954",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 119,
    "uikTvd": "4074004105955",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 120,
    "uikTvd": "4074004105956",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 121,
    "uikTvd": "4074004105957",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 122,
    "uikTvd": "4074004105958",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 123,
    "uikTvd": "4074004105959",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 124,
    "uikTvd": "4074004105960",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 125,
    "uikTvd": "4074004105961",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 126,
    "uikTvd": "4074004105962",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 127,
    "uikTvd": "4074004105963",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 128,
    "uikTvd": "4074004105964",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 129,
    "uikTvd": "4074004105965",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 130,
    "uikTvd": "4074004105966",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 131,
    "uikTvd": "4074004105967",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 132,
    "uikTvd": "4074004105968",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 133,
    "uikTvd": "4074004105969",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 134,
    "uikTvd": "4074004105970",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 135,
    "uikTvd": "4074004105971",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 136,
    "uikTvd": "4074004105972",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 137,
    "uikTvd": "4074004105973",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 138,
    "uikTvd": "4074004105974",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 139,
    "uikTvd": "4074004105975",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 140,
    "uikTvd": "4074004105976",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 141,
    "uikTvd": "4074004105977",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 142,
    "uikTvd": "4074004105978",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 143,
    "uikTvd": "4074004105979",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 144,
    "uikTvd": "4074004105980",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 145,
    "uikTvd": "4074004105981",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 146,
    "uikTvd": "4074004105982",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 147,
    "uikTvd": "4074004105983",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 148,
    "uikTvd": "4074004105984",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 149,
    "uikTvd": "4074004105985",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 150,
    "uikTvd": "4074004105986",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 151,
    "uikTvd": "4074004105987",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 152,
    "uikTvd": "4074004105988",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 153,
    "uikTvd": "4074004105989",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 154,
    "uikTvd": "4074004105990",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 155,
    "uikTvd": "4074004105991",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 156,
    "uikTvd": "4074004105992",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 157,
    "uikTvd": "4074004105993",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 158,
    "uikTvd": "4074004105994",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 159,
    "uikTvd": "4074004105995",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 160,
    "uikTvd": "4074004105996",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 161,
    "uikTvd": "4074004105997",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 162,
    "uikTvd": "4074004105998",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 163,
    "uikTvd": "4074004105999",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 164,
    "uikTvd": "4074004106000",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 165,
    "uikTvd": "4074004106001",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 166,
    "uikTvd": "4074004106002",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 167,
    "uikTvd": "4074004106003",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 168,
    "uikTvd": "4074004106004",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 169,
    "uikTvd": "4074004106005",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 170,
    "uikTvd": "4074004106006",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 171,
    "uikTvd": "4074004106007",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 172,
    "uikTvd": "4074004106008",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 173,
    "uikTvd": "4074004106009",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 174,
    "uikTvd": "4074004106010",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 175,
    "uikTvd": "4074004106011",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 176,
    "uikTvd": "4074004106012",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 177,
    "uikTvd": "4074004106013",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 178,
    "uikTvd": "4074004106014",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 179,
    "uikTvd": "4074004106015",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 180,
    "uikTvd": "4074004106016",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 181,
    "uikTvd": "4074004106017",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 182,
    "uikTvd": "4074004106018",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 183,
    "uikTvd": "4074004106019",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 184,
    "uikTvd": "4074004106020",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 185,
    "uikTvd": "4074004106021",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 186,
    "uikTvd": "4074004106022",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 187,
    "uikTvd": "4074004106023",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 188,
    "uikTvd": "4074004106024",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 189,
    "uikTvd": "4074004106025",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 190,
    "uikTvd": "4074004106026",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 191,
    "uikTvd": "4074004106027",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 192,
    "uikTvd": "4074004106028",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 193,
    "uikTvd": "4074004106029",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 194,
    "uikTvd": "4074004106030",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 195,
    "uikTvd": "4074004106031",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 196,
    "uikTvd": "4074004106032",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 197,
    "uikTvd": "4074004106033",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 198,
    "uikTvd": "4074004106034",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 199,
    "uikTvd": "4074004106035",
    "tikTvd": "2072000184621",
    "tikName": "Нальчикская городская"
  },
  {
    "uikNumber": 200,
    "uikTvd": "407401198916",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 201,
    "uikTvd": "407401198917",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 202,
    "uikTvd": "407401198918",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 203,
    "uikTvd": "407401198919",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 204,
    "uikTvd": "407401198920",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 205,
    "uikTvd": "407401198921",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 206,
    "uikTvd": "407401198922",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 207,
    "uikTvd": "407401198923",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 208,
    "uikTvd": "407401198924",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 209,
    "uikTvd": "407401198925",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 210,
    "uikTvd": "407401198926",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 211,
    "uikTvd": "407401198927",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 212,
    "uikTvd": "407401198928",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 213,
    "uikTvd": "407401198929",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 214,
    "uikTvd": "407401198930",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 215,
    "uikTvd": "407401198931",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 216,
    "uikTvd": "407401198932",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 217,
    "uikTvd": "407401198933",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 218,
    "uikTvd": "407401198934",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 219,
    "uikTvd": "407401198935",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 220,
    "uikTvd": "407401198936",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 221,
    "uikTvd": "407401198937",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 222,
    "uikTvd": "407401198938",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 223,
    "uikTvd": "407401198939",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 224,
    "uikTvd": "407401198940",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 225,
    "uikTvd": "407401198941",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 226,
    "uikTvd": "407401198942",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 227,
    "uikTvd": "407401198943",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 228,
    "uikTvd": "407401198944",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 229,
    "uikTvd": "407401198945",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 230,
    "uikTvd": "407401198946",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 231,
    "uikTvd": "407401198947",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 232,
    "uikTvd": "407401198948",
    "tikTvd": "2072000184613",
    "tikName": "Прохладненская"
  },
  {
    "uikNumber": 233,
    "uikTvd": "407400586501",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 234,
    "uikTvd": "407400586502",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 235,
    "uikTvd": "407400586503",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 236,
    "uikTvd": "407400586504",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 237,
    "uikTvd": "407400586505",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 238,
    "uikTvd": "407400586506",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 239,
    "uikTvd": "407400586507",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 240,
    "uikTvd": "407400586508",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 241,
    "uikTvd": "407400586509",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 242,
    "uikTvd": "407400586510",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 243,
    "uikTvd": "407400586511",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 244,
    "uikTvd": "407400586512",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 245,
    "uikTvd": "407400586513",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 246,
    "uikTvd": "407400586514",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 247,
    "uikTvd": "407400586515",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 248,
    "uikTvd": "407400586516",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 249,
    "uikTvd": "407400586517",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 250,
    "uikTvd": "407400586518",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 251,
    "uikTvd": "407400586519",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 252,
    "uikTvd": "407400586520",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 253,
    "uikTvd": "407400586521",
    "tikTvd": "2072000184619",
    "tikName": "Прохладненская городская"
  },
  {
    "uikNumber": 254,
    "uikTvd": "4074006106065",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 255,
    "uikTvd": "4074006106066",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 256,
    "uikTvd": "4074006106067",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 257,
    "uikTvd": "4074006106068",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 258,
    "uikTvd": "4074006106069",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 259,
    "uikTvd": "4074006106070",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 260,
    "uikTvd": "4074006106071",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 261,
    "uikTvd": "4074006106072",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 262,
    "uikTvd": "4074006106073",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 263,
    "uikTvd": "4074006106074",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 264,
    "uikTvd": "4074006106075",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 265,
    "uikTvd": "4074006106076",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 266,
    "uikTvd": "4074006106077",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 267,
    "uikTvd": "4074006106078",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 268,
    "uikTvd": "4074006106079",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 269,
    "uikTvd": "4074006106080",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 270,
    "uikTvd": "4074006106081",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 271,
    "uikTvd": "4074006106082",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 272,
    "uikTvd": "4074006106083",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 273,
    "uikTvd": "4074006106084",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 274,
    "uikTvd": "4074006106085",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 275,
    "uikTvd": "4074006106086",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 276,
    "uikTvd": "4074006106087",
    "tikTvd": "2072000184617",
    "tikName": "Терская"
  },
  {
    "uikNumber": 277,
    "uikTvd": "407400892618",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 278,
    "uikTvd": "407400892619",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 279,
    "uikTvd": "407400892620",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 280,
    "uikTvd": "407400892621",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 281,
    "uikTvd": "407400892622",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 282,
    "uikTvd": "407400892623",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 283,
    "uikTvd": "407400892624",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 284,
    "uikTvd": "407400892625",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 285,
    "uikTvd": "407400892626",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 286,
    "uikTvd": "407400892627",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 287,
    "uikTvd": "407400892628",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 288,
    "uikTvd": "407400892629",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 289,
    "uikTvd": "407400892630",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 290,
    "uikTvd": "407400892631",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 291,
    "uikTvd": "407400892632",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 292,
    "uikTvd": "407400892633",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 293,
    "uikTvd": "407400892634",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 294,
    "uikTvd": "407400892635",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 295,
    "uikTvd": "407400892636",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 296,
    "uikTvd": "407400892637",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 297,
    "uikTvd": "407400892638",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 298,
    "uikTvd": "407400892639",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 299,
    "uikTvd": "407400892640",
    "tikTvd": "2072000184615",
    "tikName": "Урванская"
  },
  {
    "uikNumber": 300,
    "uikTvd": "407400996420",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 301,
    "uikTvd": "407400996421",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 302,
    "uikTvd": "407400996422",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 303,
    "uikTvd": "407400996423",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 304,
    "uikTvd": "407400996424",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 305,
    "uikTvd": "407400996425",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 306,
    "uikTvd": "407400996426",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 307,
    "uikTvd": "407400996427",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 308,
    "uikTvd": "407400996428",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 309,
    "uikTvd": "407400996429",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 310,
    "uikTvd": "407400996430",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 311,
    "uikTvd": "407400996431",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 312,
    "uikTvd": "407400996432",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 313,
    "uikTvd": "407400996433",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 314,
    "uikTvd": "407400996434",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 315,
    "uikTvd": "407400996435",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 316,
    "uikTvd": "407400996436",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 317,
    "uikTvd": "407400996437",
    "tikTvd": "2072000184616",
    "tikName": "Чегемская"
  },
  {
    "uikNumber": 318,
    "uikTvd": "407401095239",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 319,
    "uikTvd": "407401095241",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 320,
    "uikTvd": "407401095242",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 321,
    "uikTvd": "407401095243",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 322,
    "uikTvd": "407401095244",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 323,
    "uikTvd": "407401095245",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 324,
    "uikTvd": "407401095246",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 325,
    "uikTvd": "407401095247",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 326,
    "uikTvd": "407401095248",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 327,
    "uikTvd": "407401095249",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 328,
    "uikTvd": "407401095250",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 329,
    "uikTvd": "407401095251",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 330,
    "uikTvd": "407401095252",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 331,
    "uikTvd": "407401095253",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 332,
    "uikTvd": "407401095254",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 333,
    "uikTvd": "407401095255",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 334,
    "uikTvd": "407401095256",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 335,
    "uikTvd": "407401095257",
    "tikTvd": "2072000184614",
    "tikName": "Черекская"
  },
  {
    "uikNumber": 336,
    "uikTvd": "407400792624",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 337,
    "uikTvd": "407400792626",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 338,
    "uikTvd": "407400792627",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 339,
    "uikTvd": "407400792628",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 340,
    "uikTvd": "407400792629",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 341,
    "uikTvd": "407400792630",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 342,
    "uikTvd": "407400792631",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 343,
    "uikTvd": "407400792632",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 344,
    "uikTvd": "407400792633",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 345,
    "uikTvd": "407400792634",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 346,
    "uikTvd": "407400792635",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 347,
    "uikTvd": "407400792636",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 348,
    "uikTvd": "407400792637",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 349,
    "uikTvd": "407400792638",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 350,
    "uikTvd": "407400792639",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 351,
    "uikTvd": "407400792640",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 352,
    "uikTvd": "407400792641",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 353,
    "uikTvd": "407400792642",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 354,
    "uikTvd": "407400792643",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 355,
    "uikTvd": "407400792644",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  },
  {
    "uikNumber": 356,
    "uikTvd": "407400792645",
    "tikTvd": "2072000184618",
    "tikName": "Эльбрусская"
  }
] satisfies readonly UikTikRelation[];
