// This file is autogenerated by proper-data/crawler/historical.py.
// Do not edit it manually.

export const duma_2011_uik_to_tik = [
  {
    "uikTvd": "441400183668",
    "uikNumber": 168,
    "tikTvd": "2412000214202",
    "tikName": "Алеутская",
    "region": "Камчатский край",
    "hierarchyEvidence": {
      "path": "sha256/68/68bf836c290e7511a5f40e45650c11c7ba4ff1677900930f1f9052daaed60c0a",
      "sha256": "68bf836c290e7511a5f40e45650c11c7ba4ff1677900930f1f9052daaed60c0a"
    }
  },
  {
    "uikTvd": "4414007108753",
    "uikNumber": 1,
    "tikTvd": "2412000214207",
    "tikName": "Петропавловск-Камчатская городская",
    "region": "Камчатский край",
    "hierarchyEvidence": {
      "path": "sha256/49/49900df23ac2d0a1d2389a4bc71aa6bfc0b167d8a694717f286bd9a1436d38ce",
      "sha256": "49900df23ac2d0a1d2389a4bc71aa6bfc0b167d8a694717f286bd9a1436d38ce"
    }
  },
  {
    "uikTvd": "4414007108754",
    "uikNumber": 2,
    "tikTvd": "2412000214207",
    "tikName": "Петропавловск-Камчатская городская",
    "region": "Камчатский край",
    "hierarchyEvidence": {
      "path": "sha256/49/49900df23ac2d0a1d2389a4bc71aa6bfc0b167d8a694717f286bd9a1436d38ce",
      "sha256": "49900df23ac2d0a1d2389a4bc71aa6bfc0b167d8a694717f286bd9a1436d38ce"
    }
  },
  {
    "uikTvd": "4414007108755",
    "uikNumber": 3,
    "tikTvd": "2412000214207",
    "tikName": "Петропавловск-Камчатская городская",
    "region": "Камчатский край",
    "hierarchyEvidence": {
      "path": "sha256/49/49900df23ac2d0a1d2389a4bc71aa6bfc0b167d8a694717f286bd9a1436d38ce",
      "sha256": "49900df23ac2d0a1d2389a4bc71aa6bfc0b167d8a694717f286bd9a1436d38ce"
    }
  },
  {
    "uikTvd": "477400193011",
    "uikNumber": 843,
    "tikTvd": "2772000306450",
    "tikName": "район Богородское",
    "region": "Город Москва",
    "hierarchyEvidence": {
      "path": "sha256/d0/d0651422ac69db28c9a39dcb7c6ad77170962db54ad8c6378d5ae248536bb9d5",
      "sha256": "d0651422ac69db28c9a39dcb7c6ad77170962db54ad8c6378d5ae248536bb9d5"
    }
  },
  {
    "uikTvd": "477400193012",
    "uikNumber": 844,
    "tikTvd": "2772000306450",
    "tikName": "район Богородское",
    "region": "Город Москва",
    "hierarchyEvidence": {
      "path": "sha256/d0/d0651422ac69db28c9a39dcb7c6ad77170962db54ad8c6378d5ae248536bb9d5",
      "sha256": "d0651422ac69db28c9a39dcb7c6ad77170962db54ad8c6378d5ae248536bb9d5"
    }
  },
  {
    "uikTvd": "477400193013",
    "uikNumber": 845,
    "tikTvd": "2772000306450",
    "tikName": "район Богородское",
    "region": "Город Москва",
    "hierarchyEvidence": {
      "path": "sha256/d0/d0651422ac69db28c9a39dcb7c6ad77170962db54ad8c6378d5ae248536bb9d5",
      "sha256": "d0651422ac69db28c9a39dcb7c6ad77170962db54ad8c6378d5ae248536bb9d5"
    }
  },
  {
    "uikTvd": "477409292944",
    "uikNumber": 1334,
    "tikTvd": "2772000306462",
    "tikName": "район Лефортово",
    "region": "Город Москва",
    "hierarchyEvidence": {
      "path": "sha256/22/22a352fc29d0d9476fcf235b63a8bd205b943a4669cf3ef474f439ff60bb0a1f",
      "sha256": "22a352fc29d0d9476fcf235b63a8bd205b943a4669cf3ef474f439ff60bb0a1f"
    }
  },
  {
    "uikTvd": "477409292970",
    "uikNumber": 1335,
    "tikTvd": "2772000306462",
    "tikName": "район Лефортово",
    "region": "Город Москва",
    "hierarchyEvidence": {
      "path": "sha256/22/22a352fc29d0d9476fcf235b63a8bd205b943a4669cf3ef474f439ff60bb0a1f",
      "sha256": "22a352fc29d0d9476fcf235b63a8bd205b943a4669cf3ef474f439ff60bb0a1f"
    }
  },
  {
    "uikTvd": "477409292971",
    "uikNumber": 1336,
    "tikTvd": "2772000306462",
    "tikName": "район Лефортово",
    "region": "Город Москва",
    "hierarchyEvidence": {
      "path": "sha256/22/22a352fc29d0d9476fcf235b63a8bd205b943a4669cf3ef474f439ff60bb0a1f",
      "sha256": "22a352fc29d0d9476fcf235b63a8bd205b943a4669cf3ef474f439ff60bb0a1f"
    }
  }
] as const;
