// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { UikTikRelation } from "../protocol/types";

export const president_2012_uik_to_tik_region_83 = [
  {
    "uikNumber": 1,
    "uikTvd": "4834002115329",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 2,
    "uikTvd": "4834002115331",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 3,
    "uikTvd": "4834002115333",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 4,
    "uikTvd": "4834002115335",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 5,
    "uikTvd": "4834002115337",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 6,
    "uikTvd": "4834002115339",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 7,
    "uikTvd": "4834002115341",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 8,
    "uikTvd": "4834002115343",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 9,
    "uikTvd": "4834002115345",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 10,
    "uikTvd": "4834002115347",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 11,
    "uikTvd": "4834002115349",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 12,
    "uikTvd": "4834002115351",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 13,
    "uikTvd": "4834002115353",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 14,
    "uikTvd": "4834002115355",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 15,
    "uikTvd": "4834002115357",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 16,
    "uikTvd": "4834002115359",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 17,
    "uikTvd": "4834002115361",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 18,
    "uikTvd": "4834002115363",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 19,
    "uikTvd": "4834002115365",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 20,
    "uikTvd": "4834002115367",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 21,
    "uikTvd": "4834002115369",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 22,
    "uikTvd": "4834002115371",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 23,
    "uikTvd": "4834002115373",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 24,
    "uikTvd": "4834002115375",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 25,
    "uikTvd": "4834002115377",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 26,
    "uikTvd": "4834002115379",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 27,
    "uikTvd": "4834002115381",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 28,
    "uikTvd": "4834002115383",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 29,
    "uikTvd": "4834002115385",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 30,
    "uikTvd": "4834002115387",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 31,
    "uikTvd": "4834002115389",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 32,
    "uikTvd": "4834002115391",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 33,
    "uikTvd": "4834002115393",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 34,
    "uikTvd": "4834002115395",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 35,
    "uikTvd": "4834002115397",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 36,
    "uikTvd": "4834002115399",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 37,
    "uikTvd": "4834002115401",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 38,
    "uikTvd": "4834002115403",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 39,
    "uikTvd": "4834002115405",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 40,
    "uikTvd": "4834002115407",
    "tikTvd": "2832000174568",
    "tikName": "Заполярного района"
  },
  {
    "uikNumber": 41,
    "uikTvd": "483400193466",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 42,
    "uikTvd": "483400193467",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 43,
    "uikTvd": "483400193468",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 44,
    "uikTvd": "483400193469",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 45,
    "uikTvd": "483400193470",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 46,
    "uikTvd": "483400193471",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 47,
    "uikTvd": "483400193472",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 48,
    "uikTvd": "483400193473",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 49,
    "uikTvd": "483400193474",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 50,
    "uikTvd": "483400193475",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  },
  {
    "uikNumber": 51,
    "uikTvd": "483400193476",
    "tikTvd": "2832000174567",
    "tikName": "Нарьян-Марская"
  }
] satisfies readonly UikTikRelation[];
