// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { UikTikRelation } from "../protocol/types";

export const president_2012_uik_to_tik_region_44 = [
  {
    "uikNumber": 1,
    "uikTvd": "4444001105130",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 2,
    "uikTvd": "4444001105131",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 3,
    "uikTvd": "4444001105132",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 4,
    "uikTvd": "4444001105133",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 5,
    "uikTvd": "4444001105134",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 6,
    "uikTvd": "4444001105135",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 7,
    "uikTvd": "4444001105136",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 8,
    "uikTvd": "4444001105137",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 9,
    "uikTvd": "4444001105138",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 10,
    "uikTvd": "4444001105139",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 11,
    "uikTvd": "4444001105140",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 12,
    "uikTvd": "4444001105141",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 13,
    "uikTvd": "4444001105142",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 14,
    "uikTvd": "4444001105143",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 15,
    "uikTvd": "4444001105144",
    "tikTvd": "2442000301650",
    "tikName": "Антроповская"
  },
  {
    "uikNumber": 16,
    "uikTvd": "444401294383",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 17,
    "uikTvd": "4444027108289",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 18,
    "uikTvd": "4444027108290",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 19,
    "uikTvd": "4444027108291",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 20,
    "uikTvd": "4444027108292",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 21,
    "uikTvd": "4444027108293",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 22,
    "uikTvd": "4444027108294",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 23,
    "uikTvd": "4444027108295",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 24,
    "uikTvd": "4444027108296",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 25,
    "uikTvd": "4444027108297",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 26,
    "uikTvd": "4444027108298",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 27,
    "uikTvd": "4444027108299",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 28,
    "uikTvd": "4444027108300",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 29,
    "uikTvd": "4444027108301",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 30,
    "uikTvd": "4444027108302",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 31,
    "uikTvd": "4444027108303",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 32,
    "uikTvd": "4444027108304",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 33,
    "uikTvd": "4444027108305",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 34,
    "uikTvd": "4444027108306",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 35,
    "uikTvd": "4444027108307",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 36,
    "uikTvd": "4444027108308",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 37,
    "uikTvd": "4444027108309",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 38,
    "uikTvd": "4444027108310",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 39,
    "uikTvd": "4444027108311",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 40,
    "uikTvd": "4444027108312",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 41,
    "uikTvd": "4444027108313",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 42,
    "uikTvd": "4444027108314",
    "tikTvd": "2442000301684",
    "tikName": "Буйская"
  },
  {
    "uikNumber": 43,
    "uikTvd": "444400295894",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 44,
    "uikTvd": "444400295895",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 45,
    "uikTvd": "444400295896",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 46,
    "uikTvd": "444400295897",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 47,
    "uikTvd": "444400295898",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 48,
    "uikTvd": "444400295899",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 49,
    "uikTvd": "444400295900",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 50,
    "uikTvd": "444400295901",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 51,
    "uikTvd": "444400295902",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 52,
    "uikTvd": "444400295903",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 53,
    "uikTvd": "444400295904",
    "tikTvd": "2442000301667",
    "tikName": "Буйская городская"
  },
  {
    "uikNumber": 54,
    "uikTvd": "4444008255073",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 55,
    "uikTvd": "4444008255302",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 59,
    "uikTvd": "4444025109005",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 60,
    "uikTvd": "4444025109007",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 61,
    "uikTvd": "4444025109008",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 62,
    "uikTvd": "444402194689",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 63,
    "uikTvd": "444402194690",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 64,
    "uikTvd": "444402194691",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 65,
    "uikTvd": "444402194692",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 66,
    "uikTvd": "444402194693",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 67,
    "uikTvd": "444402194694",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 68,
    "uikTvd": "444402194695",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 69,
    "uikTvd": "444402194696",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 70,
    "uikTvd": "444402194700",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 71,
    "uikTvd": "444402194697",
    "tikTvd": "2442000301662",
    "tikName": "Пыщугская"
  },
  {
    "uikNumber": 72,
    "uikTvd": "444401393621",
    "tikTvd": "2442000301683",
    "tikName": "Межевская"
  },
  {
    "uikNumber": 73,
    "uikTvd": "444401393623",
    "tikTvd": "2442000301683",
    "tikName": "Межевская"
  },
  {
    "uikNumber": 74,
    "uikTvd": "444401393625",
    "tikTvd": "2442000301683",
    "tikName": "Межевская"
  },
  {
    "uikNumber": 75,
    "uikTvd": "444401393627",
    "tikTvd": "2442000301683",
    "tikName": "Межевская"
  },
  {
    "uikNumber": 76,
    "uikTvd": "444401393629",
    "tikTvd": "2442000301683",
    "tikName": "Межевская"
  },
  {
    "uikNumber": 77,
    "uikTvd": "444401393631",
    "tikTvd": "2442000301683",
    "tikName": "Межевская"
  },
  {
    "uikNumber": 78,
    "uikTvd": "444401393633",
    "tikTvd": "2442000301683",
    "tikName": "Межевская"
  },
  {
    "uikNumber": 79,
    "uikTvd": "444401393635",
    "tikTvd": "2442000301683",
    "tikName": "Межевская"
  },
  {
    "uikNumber": 80,
    "uikTvd": "4444004103566",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 81,
    "uikTvd": "4444004103569",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 82,
    "uikTvd": "4444004103570",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 83,
    "uikTvd": "4444004103571",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 84,
    "uikTvd": "4444004103572",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 85,
    "uikTvd": "4444004103573",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 86,
    "uikTvd": "4444004103574",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 87,
    "uikTvd": "4444004103575",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 88,
    "uikTvd": "4444004103576",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 89,
    "uikTvd": "4444004103577",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 90,
    "uikTvd": "4444004103578",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 91,
    "uikTvd": "4444004103579",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 92,
    "uikTvd": "4444004103580",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 93,
    "uikTvd": "4444004103581",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 94,
    "uikTvd": "4444004103582",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 95,
    "uikTvd": "4444004103583",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 96,
    "uikTvd": "4444004103584",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 97,
    "uikTvd": "4444004103585",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 98,
    "uikTvd": "4444004103586",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 99,
    "uikTvd": "4444004103587",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 100,
    "uikTvd": "4444004103588",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 101,
    "uikTvd": "4444004103589",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 102,
    "uikTvd": "4444004103590",
    "tikTvd": "2442000301672",
    "tikName": "Вохомская"
  },
  {
    "uikNumber": 103,
    "uikTvd": "4444028107720",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 104,
    "uikTvd": "4444028107721",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 105,
    "uikTvd": "4444028107722",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 106,
    "uikTvd": "4444028107723",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 107,
    "uikTvd": "4444028107724",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 108,
    "uikTvd": "4444028107725",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 109,
    "uikTvd": "4444028107726",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 110,
    "uikTvd": "4444028107727",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 111,
    "uikTvd": "4444028107728",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 112,
    "uikTvd": "4444028107729",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 113,
    "uikTvd": "4444028107730",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 114,
    "uikTvd": "4444028107731",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 115,
    "uikTvd": "4444028107732",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 116,
    "uikTvd": "4444028107733",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 117,
    "uikTvd": "4444028107734",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 118,
    "uikTvd": "4444028107735",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 119,
    "uikTvd": "4444028107736",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 120,
    "uikTvd": "4444028107737",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 121,
    "uikTvd": "4444028107738",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 122,
    "uikTvd": "4444028107739",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 123,
    "uikTvd": "4444028107740",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 124,
    "uikTvd": "4444028107741",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 125,
    "uikTvd": "4444028107742",
    "tikTvd": "2442000301664",
    "tikName": "Галичская"
  },
  {
    "uikNumber": 126,
    "uikTvd": "444400592469",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 127,
    "uikTvd": "444400592470",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 128,
    "uikTvd": "444400592471",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 129,
    "uikTvd": "444402095843",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 130,
    "uikTvd": "444400592473",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 131,
    "uikTvd": "444400592474",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 132,
    "uikTvd": "444400592475",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 133,
    "uikTvd": "444400592476",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 134,
    "uikTvd": "444400592477",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 135,
    "uikTvd": "444400592478",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 136,
    "uikTvd": "444400592479",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 137,
    "uikTvd": "444400592480",
    "tikTvd": "2442000301673",
    "tikName": "Галичская городская"
  },
  {
    "uikNumber": 138,
    "uikTvd": "4444006106609",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 139,
    "uikTvd": "4444006106610",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 140,
    "uikTvd": "4444006106611",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 141,
    "uikTvd": "4444006106612",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 142,
    "uikTvd": "4444006106613",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 143,
    "uikTvd": "4444006106614",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 144,
    "uikTvd": "4444006106615",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 145,
    "uikTvd": "4444006106616",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 146,
    "uikTvd": "4444006106617",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 147,
    "uikTvd": "4444006106618",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 148,
    "uikTvd": "4444006106619",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 149,
    "uikTvd": "4444006106620",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 150,
    "uikTvd": "4444006106621",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 151,
    "uikTvd": "4444006106622",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 152,
    "uikTvd": "4444006106623",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 153,
    "uikTvd": "4444006106624",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 154,
    "uikTvd": "4444006106625",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 155,
    "uikTvd": "4444006106626",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 156,
    "uikTvd": "4444006106627",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 157,
    "uikTvd": "4444006106628",
    "tikTvd": "2442000301674",
    "tikName": "Кадыйская"
  },
  {
    "uikNumber": 158,
    "uikTvd": "4444007102428",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 159,
    "uikTvd": "4444007102429",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 160,
    "uikTvd": "4444007102430",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 161,
    "uikTvd": "4444007102431",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 162,
    "uikTvd": "4444007102432",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 163,
    "uikTvd": "4444007102433",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 164,
    "uikTvd": "4444007102434",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 165,
    "uikTvd": "4444007102435",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 166,
    "uikTvd": "4444007102436",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 167,
    "uikTvd": "4444007102437",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 168,
    "uikTvd": "4444007102438",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 169,
    "uikTvd": "4444007102439",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 170,
    "uikTvd": "4444007102440",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 171,
    "uikTvd": "4444007102441",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 172,
    "uikTvd": "4444007102442",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 173,
    "uikTvd": "4444007102443",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 174,
    "uikTvd": "4444007102444",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 175,
    "uikTvd": "4444007102445",
    "tikTvd": "2442000301670",
    "tikName": "Кологривская"
  },
  {
    "uikNumber": 176,
    "uikTvd": "4444009119163",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 177,
    "uikTvd": "4444009119164",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 178,
    "uikTvd": "4444009119165",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 179,
    "uikTvd": "4444009119166",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 180,
    "uikTvd": "4444009119167",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 181,
    "uikTvd": "4444009119168",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 182,
    "uikTvd": "4444009119169",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 183,
    "uikTvd": "4444009119170",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 184,
    "uikTvd": "4444009119171",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 185,
    "uikTvd": "4444009119172",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 186,
    "uikTvd": "4444009119173",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 187,
    "uikTvd": "4444009119174",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 188,
    "uikTvd": "4444009119175",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 189,
    "uikTvd": "4444009119176",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 190,
    "uikTvd": "4444009119177",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 191,
    "uikTvd": "4444009119178",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 192,
    "uikTvd": "4444009119179",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 193,
    "uikTvd": "4444009119180",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 194,
    "uikTvd": "4444009119181",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 195,
    "uikTvd": "4444009119182",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 196,
    "uikTvd": "4444009119183",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 197,
    "uikTvd": "4444009119184",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 198,
    "uikTvd": "4444009119185",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 199,
    "uikTvd": "4444009119186",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 200,
    "uikTvd": "4444009119187",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 201,
    "uikTvd": "4444009119188",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 202,
    "uikTvd": "4444009119189",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 203,
    "uikTvd": "4444009119190",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 204,
    "uikTvd": "4444009119191",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 205,
    "uikTvd": "4444009119192",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 206,
    "uikTvd": "4444009119193",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 207,
    "uikTvd": "4444009119194",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 208,
    "uikTvd": "4444009119195",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 209,
    "uikTvd": "4444009119196",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 210,
    "uikTvd": "4444009119197",
    "tikTvd": "2442000301671",
    "tikName": "Костромская"
  },
  {
    "uikNumber": 211,
    "uikTvd": "4444008158617",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 212,
    "uikTvd": "4444008158112",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 213,
    "uikTvd": "4444008158113",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 214,
    "uikTvd": "4444008158114",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 215,
    "uikTvd": "4444008158115",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 216,
    "uikTvd": "4444008158116",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 217,
    "uikTvd": "4444008158117",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 218,
    "uikTvd": "4444008158118",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 219,
    "uikTvd": "4444008158119",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 220,
    "uikTvd": "4444008158120",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 221,
    "uikTvd": "4444008158121",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 222,
    "uikTvd": "4444008158122",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 223,
    "uikTvd": "4444008158123",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 224,
    "uikTvd": "4444008158124",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 225,
    "uikTvd": "4444008158125",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 226,
    "uikTvd": "4444008158126",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 227,
    "uikTvd": "4444008158127",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 228,
    "uikTvd": "4444008158128",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 229,
    "uikTvd": "4444008158129",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 230,
    "uikTvd": "4444008158130",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 231,
    "uikTvd": "4444008158131",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 232,
    "uikTvd": "4444008158132",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 233,
    "uikTvd": "4444008158133",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 234,
    "uikTvd": "4444008158134",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 235,
    "uikTvd": "4444008158135",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 236,
    "uikTvd": "4444008158136",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 237,
    "uikTvd": "4444008158137",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 238,
    "uikTvd": "4444008158138",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 239,
    "uikTvd": "4444008158139",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 240,
    "uikTvd": "4444008158140",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 241,
    "uikTvd": "4444008158141",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 242,
    "uikTvd": "4444008158142",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 243,
    "uikTvd": "4444008158143",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 244,
    "uikTvd": "4444008158144",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 245,
    "uikTvd": "4444008158145",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 246,
    "uikTvd": "4444008158146",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 247,
    "uikTvd": "4444008158147",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 248,
    "uikTvd": "4444008158148",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 249,
    "uikTvd": "4444008158149",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 250,
    "uikTvd": "4444008158150",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 251,
    "uikTvd": "4444008158151",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 252,
    "uikTvd": "4444008158152",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 253,
    "uikTvd": "4444008158153",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 254,
    "uikTvd": "4444008158154",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 255,
    "uikTvd": "4444008158155",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 256,
    "uikTvd": "4444008158156",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 257,
    "uikTvd": "4444008158157",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 258,
    "uikTvd": "4444008158158",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 259,
    "uikTvd": "4444008158159",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 260,
    "uikTvd": "4444008158160",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 261,
    "uikTvd": "4444008158161",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 262,
    "uikTvd": "4444008158162",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 263,
    "uikTvd": "4444008158163",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 264,
    "uikTvd": "4444008158164",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 265,
    "uikTvd": "4444008158165",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 266,
    "uikTvd": "4444008158166",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 267,
    "uikTvd": "4444008158167",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 268,
    "uikTvd": "4444008158168",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 269,
    "uikTvd": "4444008158169",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 270,
    "uikTvd": "4444008158170",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 271,
    "uikTvd": "4444008158171",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 272,
    "uikTvd": "4444008158172",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 273,
    "uikTvd": "4444008158173",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 274,
    "uikTvd": "4444008158174",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 275,
    "uikTvd": "4444008158175",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 276,
    "uikTvd": "4444008158176",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 277,
    "uikTvd": "4444008158177",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 278,
    "uikTvd": "4444008158178",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 279,
    "uikTvd": "4444008158179",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 280,
    "uikTvd": "4444008158180",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 281,
    "uikTvd": "4444008158181",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 282,
    "uikTvd": "4444008158182",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 283,
    "uikTvd": "4444008158183",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 284,
    "uikTvd": "4444008158184",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 285,
    "uikTvd": "4444008158185",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 286,
    "uikTvd": "4444008158186",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 287,
    "uikTvd": "4444008158187",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 288,
    "uikTvd": "4444008158188",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 289,
    "uikTvd": "4444008158189",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 290,
    "uikTvd": "4444008158190",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 291,
    "uikTvd": "4444008158191",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 292,
    "uikTvd": "4444008158192",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 293,
    "uikTvd": "4444008158193",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 294,
    "uikTvd": "4444008158194",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 295,
    "uikTvd": "4444008158195",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 296,
    "uikTvd": "4444008158196",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 297,
    "uikTvd": "4444008158197",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 298,
    "uikTvd": "4444008158198",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 299,
    "uikTvd": "4444008158199",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 300,
    "uikTvd": "4444008158200",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 301,
    "uikTvd": "4444008158201",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 302,
    "uikTvd": "4444008158202",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 303,
    "uikTvd": "4444008158203",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 304,
    "uikTvd": "4444008158204",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 305,
    "uikTvd": "4444008158205",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 306,
    "uikTvd": "4444008158206",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 307,
    "uikTvd": "4444008158207",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 308,
    "uikTvd": "4444008158208",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 309,
    "uikTvd": "4444008158209",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 310,
    "uikTvd": "4444008158210",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 311,
    "uikTvd": "4444008158211",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 312,
    "uikTvd": "4444008158212",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 313,
    "uikTvd": "4444008158213",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 314,
    "uikTvd": "4444008158214",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 315,
    "uikTvd": "4444008158215",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 316,
    "uikTvd": "4444008158216",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 317,
    "uikTvd": "4444008158217",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 318,
    "uikTvd": "4444008158218",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 319,
    "uikTvd": "4444008158219",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 320,
    "uikTvd": "4444008158220",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 321,
    "uikTvd": "4444008158221",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 322,
    "uikTvd": "4444008158222",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 323,
    "uikTvd": "4444008158223",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 324,
    "uikTvd": "4444008158618",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 325,
    "uikTvd": "4444008158619",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 326,
    "uikTvd": "4444008158620",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 327,
    "uikTvd": "4444010110644",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 328,
    "uikTvd": "4444010110645",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 329,
    "uikTvd": "4444010110646",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 330,
    "uikTvd": "4444010110647",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 331,
    "uikTvd": "4444010110648",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 332,
    "uikTvd": "4444010110649",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 333,
    "uikTvd": "4444010110650",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 334,
    "uikTvd": "4444010110651",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 335,
    "uikTvd": "4444010110652",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 336,
    "uikTvd": "4444010110653",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 337,
    "uikTvd": "4444010110654",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 338,
    "uikTvd": "4444010110655",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 339,
    "uikTvd": "4444010110656",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 340,
    "uikTvd": "4444010110657",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 341,
    "uikTvd": "4444010110658",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 342,
    "uikTvd": "4444010110659",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 343,
    "uikTvd": "4444010110660",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 344,
    "uikTvd": "4444010110661",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 345,
    "uikTvd": "4444010110662",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 346,
    "uikTvd": "4444010110663",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 347,
    "uikTvd": "4444010110664",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 348,
    "uikTvd": "4444010110665",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 349,
    "uikTvd": "4444011116224",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 350,
    "uikTvd": "4444011116225",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 351,
    "uikTvd": "4444011116226",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 352,
    "uikTvd": "4444011116227",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 353,
    "uikTvd": "4444011116228",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 354,
    "uikTvd": "4444011116229",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 355,
    "uikTvd": "4444011116230",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 356,
    "uikTvd": "4444011116231",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 357,
    "uikTvd": "4444011116232",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 358,
    "uikTvd": "4444011116233",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 359,
    "uikTvd": "4444011116234",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 360,
    "uikTvd": "4444011116235",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 361,
    "uikTvd": "4444011116236",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 362,
    "uikTvd": "4444011116237",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 363,
    "uikTvd": "4444011116238",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 364,
    "uikTvd": "4444011116239",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 365,
    "uikTvd": "4444011116240",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 366,
    "uikTvd": "4444011116241",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 367,
    "uikTvd": "4444011116242",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 368,
    "uikTvd": "4444011116243",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 369,
    "uikTvd": "4444011116244",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 370,
    "uikTvd": "4444011116245",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 371,
    "uikTvd": "4444011116246",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 372,
    "uikTvd": "4444011116247",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 373,
    "uikTvd": "4444011116248",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 374,
    "uikTvd": "4444011116249",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 375,
    "uikTvd": "4444011116250",
    "tikTvd": "2442000301675",
    "tikName": "Макарьевская"
  },
  {
    "uikNumber": 376,
    "uikTvd": "4444029102805",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 377,
    "uikTvd": "4444029102806",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 378,
    "uikTvd": "4444029102807",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 379,
    "uikTvd": "4444029102808",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 380,
    "uikTvd": "4444029102809",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 381,
    "uikTvd": "4444029102810",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 382,
    "uikTvd": "4444029102811",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 383,
    "uikTvd": "4444029102812",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 384,
    "uikTvd": "4444029102813",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 385,
    "uikTvd": "4444029102814",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 386,
    "uikTvd": "4444029102815",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 387,
    "uikTvd": "4444029102816",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 388,
    "uikTvd": "4444029102817",
    "tikTvd": "2442000301666",
    "tikName": "Мантуровская"
  },
  {
    "uikNumber": 389,
    "uikTvd": "444401293248",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 390,
    "uikTvd": "444401293249",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 391,
    "uikTvd": "444401293250",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 392,
    "uikTvd": "444401293251",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 393,
    "uikTvd": "444401293252",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 394,
    "uikTvd": "444401293253",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 395,
    "uikTvd": "444401293254",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 396,
    "uikTvd": "444401293255",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 397,
    "uikTvd": "444401293256",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 398,
    "uikTvd": "444401293257",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  },
  {
    "uikNumber": 399,
    "uikTvd": "4444031111215",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 400,
    "uikTvd": "4444031111216",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 401,
    "uikTvd": "4444031111217",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 402,
    "uikTvd": "4444031111218",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 403,
    "uikTvd": "4444031111219",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 404,
    "uikTvd": "4444031111220",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 405,
    "uikTvd": "4444031111221",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 406,
    "uikTvd": "4444031111222",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 407,
    "uikTvd": "4444031111223",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 408,
    "uikTvd": "4444031111224",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 409,
    "uikTvd": "4444031111225",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 410,
    "uikTvd": "4444031111226",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 411,
    "uikTvd": "4444031111227",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 412,
    "uikTvd": "4444031111228",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 413,
    "uikTvd": "4444031111229",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 414,
    "uikTvd": "4444031111230",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 415,
    "uikTvd": "4444031111231",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 416,
    "uikTvd": "4444031111232",
    "tikTvd": "2442000301665",
    "tikName": "Шарьинская"
  },
  {
    "uikNumber": 417,
    "uikTvd": "4444008254735",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 418,
    "uikTvd": "4444008254736",
    "tikTvd": "2442000301669",
    "tikName": "Костромская городская"
  },
  {
    "uikNumber": 422,
    "uikTvd": "4444014106544",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 423,
    "uikTvd": "4444014106545",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 424,
    "uikTvd": "4444014106546",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 425,
    "uikTvd": "4444014106547",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 426,
    "uikTvd": "4444014106548",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 427,
    "uikTvd": "4444014106549",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 428,
    "uikTvd": "4444014106550",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 429,
    "uikTvd": "4444014106551",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 430,
    "uikTvd": "4444014106552",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 431,
    "uikTvd": "4444014106553",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 432,
    "uikTvd": "4444014106554",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 433,
    "uikTvd": "4444014106555",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 434,
    "uikTvd": "4444014106556",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 435,
    "uikTvd": "4444014106557",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 436,
    "uikTvd": "4444014106558",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 437,
    "uikTvd": "4444014106559",
    "tikTvd": "2442000301682",
    "tikName": "Нейская"
  },
  {
    "uikNumber": 438,
    "uikTvd": "4444010110666",
    "tikTvd": "2442000301668",
    "tikName": "Красносельская"
  },
  {
    "uikNumber": 439,
    "uikTvd": "4444015123893",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 440,
    "uikTvd": "4444015123894",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 441,
    "uikTvd": "4444015123895",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 442,
    "uikTvd": "4444015123896",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 443,
    "uikTvd": "4444015123897",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 444,
    "uikTvd": "4444015123898",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 445,
    "uikTvd": "4444015123899",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 446,
    "uikTvd": "4444015123900",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 447,
    "uikTvd": "4444015123901",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 448,
    "uikTvd": "4444015123902",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 449,
    "uikTvd": "4444015123903",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 450,
    "uikTvd": "4444015123904",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 451,
    "uikTvd": "4444015123905",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 452,
    "uikTvd": "4444015123906",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 453,
    "uikTvd": "4444015123907",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 454,
    "uikTvd": "4444015123908",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 455,
    "uikTvd": "4444015123909",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 456,
    "uikTvd": "4444015123910",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 457,
    "uikTvd": "4444015123911",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 458,
    "uikTvd": "4444015123912",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 459,
    "uikTvd": "4444015123913",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 460,
    "uikTvd": "4444015123914",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 461,
    "uikTvd": "4444015123915",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 462,
    "uikTvd": "4444015123916",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 463,
    "uikTvd": "4444015123917",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 464,
    "uikTvd": "4444015123918",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 465,
    "uikTvd": "4444015123919",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 466,
    "uikTvd": "4444015123920",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 467,
    "uikTvd": "4444015123921",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 468,
    "uikTvd": "4444015123922",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 469,
    "uikTvd": "4444015123923",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 470,
    "uikTvd": "4444015123924",
    "tikTvd": "2442000301681",
    "tikName": "Нерехтская"
  },
  {
    "uikNumber": 471,
    "uikTvd": "444401696888",
    "tikTvd": "2442000301678",
    "tikName": "Октябрьская"
  },
  {
    "uikNumber": 472,
    "uikTvd": "444401696889",
    "tikTvd": "2442000301678",
    "tikName": "Октябрьская"
  },
  {
    "uikNumber": 473,
    "uikTvd": "444401696890",
    "tikTvd": "2442000301678",
    "tikName": "Октябрьская"
  },
  {
    "uikNumber": 474,
    "uikTvd": "444401696891",
    "tikTvd": "2442000301678",
    "tikName": "Октябрьская"
  },
  {
    "uikNumber": 475,
    "uikTvd": "444401696892",
    "tikTvd": "2442000301678",
    "tikName": "Октябрьская"
  },
  {
    "uikNumber": 476,
    "uikTvd": "444401696893",
    "tikTvd": "2442000301678",
    "tikName": "Октябрьская"
  },
  {
    "uikNumber": 477,
    "uikTvd": "444401696894",
    "tikTvd": "2442000301678",
    "tikName": "Октябрьская"
  },
  {
    "uikNumber": 478,
    "uikTvd": "444401696895",
    "tikTvd": "2442000301678",
    "tikName": "Октябрьская"
  },
  {
    "uikNumber": 479,
    "uikTvd": "444401696896",
    "tikTvd": "2442000301678",
    "tikName": "Октябрьская"
  },
  {
    "uikNumber": 480,
    "uikTvd": "4444017107416",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 481,
    "uikTvd": "4444017107417",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 482,
    "uikTvd": "4444017107418",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 483,
    "uikTvd": "4444017107419",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 484,
    "uikTvd": "4444017107420",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 485,
    "uikTvd": "4444017107421",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 486,
    "uikTvd": "4444017107422",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 487,
    "uikTvd": "4444017107423",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 488,
    "uikTvd": "4444017107424",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 489,
    "uikTvd": "4444017107425",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 490,
    "uikTvd": "4444017107426",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 491,
    "uikTvd": "4444017107427",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 492,
    "uikTvd": "4444017107428",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 493,
    "uikTvd": "4444017107429",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 494,
    "uikTvd": "4444017107430",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 495,
    "uikTvd": "4444017107431",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 496,
    "uikTvd": "4444017107432",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 497,
    "uikTvd": "4444017107433",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 498,
    "uikTvd": "4444017107434",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 499,
    "uikTvd": "4444017107435",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 500,
    "uikTvd": "4444017107436",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 501,
    "uikTvd": "4444017107437",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 502,
    "uikTvd": "4444017107438",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 503,
    "uikTvd": "4444017107439",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 504,
    "uikTvd": "4444017107440",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 505,
    "uikTvd": "4444017107441",
    "tikTvd": "2442000301680",
    "tikName": "Островская"
  },
  {
    "uikNumber": 506,
    "uikTvd": "444401895912",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 507,
    "uikTvd": "444401895913",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 508,
    "uikTvd": "444401895914",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 509,
    "uikTvd": "444401895915",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 510,
    "uikTvd": "444401895916",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 511,
    "uikTvd": "444401895917",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 512,
    "uikTvd": "444401895918",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 513,
    "uikTvd": "444401895919",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 514,
    "uikTvd": "444401895920",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 515,
    "uikTvd": "444401895921",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 516,
    "uikTvd": "444401895922",
    "tikTvd": "2442000301679",
    "tikName": "Павинская"
  },
  {
    "uikNumber": 517,
    "uikTvd": "444401997332",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 518,
    "uikTvd": "444401997333",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 519,
    "uikTvd": "444401997334",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 520,
    "uikTvd": "444401997335",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 521,
    "uikTvd": "444401997336",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 522,
    "uikTvd": "444401997337",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 523,
    "uikTvd": "444401997338",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 524,
    "uikTvd": "444401997339",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 525,
    "uikTvd": "444401997340",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 526,
    "uikTvd": "444401997341",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 527,
    "uikTvd": "444401997342",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 528,
    "uikTvd": "444401997343",
    "tikTvd": "2442000301676",
    "tikName": "Парфеньевская"
  },
  {
    "uikNumber": 529,
    "uikTvd": "444402095824",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 530,
    "uikTvd": "444402095832",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 531,
    "uikTvd": "444402095826",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 532,
    "uikTvd": "444402095834",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 533,
    "uikTvd": "444402095828",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 534,
    "uikTvd": "444402095830",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 535,
    "uikTvd": "444402095836",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 536,
    "uikTvd": "444402095838",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 537,
    "uikTvd": "444402095840",
    "tikTvd": "2442000301686",
    "tikName": "Поназыревская"
  },
  {
    "uikNumber": 538,
    "uikTvd": "4444023107677",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 539,
    "uikTvd": "444400388471",
    "tikTvd": "2442000301677",
    "tikName": "Волгореченская городская"
  },
  {
    "uikNumber": 540,
    "uikTvd": "444400388472",
    "tikTvd": "2442000301677",
    "tikName": "Волгореченская городская"
  },
  {
    "uikNumber": 541,
    "uikTvd": "444400388473",
    "tikTvd": "2442000301677",
    "tikName": "Волгореченская городская"
  },
  {
    "uikNumber": 542,
    "uikTvd": "444400388474",
    "tikTvd": "2442000301677",
    "tikName": "Волгореченская городская"
  },
  {
    "uikNumber": 543,
    "uikTvd": "444400388475",
    "tikTvd": "2442000301677",
    "tikName": "Волгореченская городская"
  },
  {
    "uikNumber": 544,
    "uikTvd": "444400388476",
    "tikTvd": "2442000301677",
    "tikName": "Волгореченская городская"
  },
  {
    "uikNumber": 545,
    "uikTvd": "444402693783",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 546,
    "uikTvd": "444402693784",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 547,
    "uikTvd": "444402693785",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 548,
    "uikTvd": "444402693786",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 549,
    "uikTvd": "444402693787",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 550,
    "uikTvd": "444402693788",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 551,
    "uikTvd": "444402693789",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 552,
    "uikTvd": "444402693790",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 553,
    "uikTvd": "444402693791",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 554,
    "uikTvd": "444402693792",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 555,
    "uikTvd": "444402693793",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 556,
    "uikTvd": "444402693794",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 557,
    "uikTvd": "444402693795",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 558,
    "uikTvd": "444402693796",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 559,
    "uikTvd": "444402693797",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 560,
    "uikTvd": "444402693798",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 561,
    "uikTvd": "444402693799",
    "tikTvd": "2442000301658",
    "tikName": "Шарьинская городская"
  },
  {
    "uikNumber": 562,
    "uikTvd": "4444022112723",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 563,
    "uikTvd": "4444022112724",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 564,
    "uikTvd": "4444022112725",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 565,
    "uikTvd": "4444022112726",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 566,
    "uikTvd": "4444022112727",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 567,
    "uikTvd": "4444022112728",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 568,
    "uikTvd": "4444022112729",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 569,
    "uikTvd": "4444022112730",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 570,
    "uikTvd": "4444022112731",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 571,
    "uikTvd": "4444022112732",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 572,
    "uikTvd": "4444022112733",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 573,
    "uikTvd": "4444022112734",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 574,
    "uikTvd": "4444022112735",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 575,
    "uikTvd": "4444022112736",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 576,
    "uikTvd": "4444022112737",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 577,
    "uikTvd": "4444022112738",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 578,
    "uikTvd": "4444022112739",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 579,
    "uikTvd": "4444022112740",
    "tikTvd": "2442000301663",
    "tikName": "Солигаличская"
  },
  {
    "uikNumber": 584,
    "uikTvd": "4444023107678",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 585,
    "uikTvd": "4444023107679",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 586,
    "uikTvd": "4444023107680",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 587,
    "uikTvd": "4444023107681",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 588,
    "uikTvd": "4444023107682",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 589,
    "uikTvd": "4444023107683",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 590,
    "uikTvd": "4444023107684",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 591,
    "uikTvd": "4444023107685",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 592,
    "uikTvd": "4444023107686",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 593,
    "uikTvd": "4444023107687",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 594,
    "uikTvd": "4444023107688",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 595,
    "uikTvd": "4444023107689",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 596,
    "uikTvd": "4444023107690",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 597,
    "uikTvd": "4444023107691",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 598,
    "uikTvd": "4444023107692",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 599,
    "uikTvd": "4444023107693",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 600,
    "uikTvd": "4444023107694",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 601,
    "uikTvd": "4444023107695",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 602,
    "uikTvd": "4444023107696",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 603,
    "uikTvd": "4444023107697",
    "tikTvd": "2442000301661",
    "tikName": "Судиславская"
  },
  {
    "uikNumber": 604,
    "uikTvd": "4444024100625",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 605,
    "uikTvd": "4444024100626",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 606,
    "uikTvd": "4444024100627",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 607,
    "uikTvd": "4444024100628",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 608,
    "uikTvd": "4444024100629",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 609,
    "uikTvd": "4444024100630",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 610,
    "uikTvd": "4444024100631",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 611,
    "uikTvd": "4444024100632",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 612,
    "uikTvd": "4444024100633",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 613,
    "uikTvd": "4444024100634",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 614,
    "uikTvd": "4444024100635",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 615,
    "uikTvd": "4444024100636",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 616,
    "uikTvd": "4444024100637",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 617,
    "uikTvd": "4444024100638",
    "tikTvd": "2442000301660",
    "tikName": "Сусанинская"
  },
  {
    "uikNumber": 618,
    "uikTvd": "4444025109009",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 619,
    "uikTvd": "4444025109010",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 620,
    "uikTvd": "4444025109011",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 621,
    "uikTvd": "4444025109012",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 622,
    "uikTvd": "4444025109013",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 623,
    "uikTvd": "4444025109014",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 624,
    "uikTvd": "4444025109015",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 625,
    "uikTvd": "4444025109016",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 626,
    "uikTvd": "4444025109017",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 627,
    "uikTvd": "4444025109018",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 628,
    "uikTvd": "4444025109019",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 629,
    "uikTvd": "4444025109020",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 630,
    "uikTvd": "4444025109021",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 631,
    "uikTvd": "4444025109022",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 632,
    "uikTvd": "4444025109023",
    "tikTvd": "2442000301659",
    "tikName": "Чухломская"
  },
  {
    "uikNumber": 633,
    "uikTvd": "444401293258",
    "tikTvd": "2442000301685",
    "tikName": "Мантуровская городская"
  }
] satisfies readonly UikTikRelation[];
