// This file is autogenerated by proper-data/crawler/historical.py.
// Do not edit it manually.

import type { HistoricalUikProtocol } from "../../types";

export const duma_2003_uik_428_477409270416 = {
  "election": "2003-duma",
  "electionVrn": "100100095619",
  "protocol": "candidate",
  "reportType": 428,
  "commission": {
    "level": "uik",
    "name": "УИК №1325",
    "tvd": "477409270416",
    "tikTvd": "377300170415",
    "region": "Город Москва"
  },
  "accounting": {
    "Число избирателей, включенных в списки": 1966,
    "Число бюллетеней, полученных участковыми комиссиями": 1990,
    "Число бюллетеней, выданных избирателям, проголосовавшим досрочно": 0,
    "Число избирательных бюллетеней, выданных избирателям на избирательном участке": 907,
    "Число бюллетеней, выданных избирателям, проголосовавшим вне помещений для голосования": 29,
    "Число погашенных бюллетеней": 1054,
    "Число бюллетеней в переносных ящиках для голосования": 29,
    "Число бюллетеней в стационарных ящиках для голосования": 907,
    "Число недействительных бюллетеней": 17,
    "Число действительных бюллетеней": 919,
    "Число открепительных удостоверений, полученных участковыми комиссиями": 50,
    "Число открепительных удостоверений, выданных участковыми комиссиями": 30,
    "Число избирателей, проголосовавших по открепительным удостоверениям": 8,
    "Число погашенных открепительных удостоверений": 20,
    "Число открепительных удостоверений, выданных ТИК": 0,
    "Число утраченных бюллетеней": 0,
    "Число не учтенных при получении бюллетеней": 0,
    "Число утраченных открепительных удостоверений": 0,
    "Число не учтенных открепительных удостоверений": 0
  },
  "votes": {
    "1. Городилин Сергей Владимирович": 125,
    "2. Драганов Валерий Гаврилович": 352,
    "3. Каминский Юрий Викторович": 37,
    "4. Козлов Александр Петрович": 55,
    "5. Московченко Николай Михайлович": 117,
    "6. Новичихина Надежда Васильевна": 46,
    "Против всех": 187
  },
  "validation": {
    "vote_sum": 919,
    "valid_ballots": 919,
    "vote_sum_matches_valid_ballots": true
  },
  "source": {
    "requestedUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=773001001&vrn=100100095619&global=true&prver=0&pronetvd=0&tvd=477409270416&region=77&sub_region=77&vibid=477409270416&type=428",
    "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=773001001&vrn=100100095619&global=true&prver=0&pronetvd=0&tvd=477409270416&region=77&sub_region=77&vibid=477409270416&type=428",
    "retrievedAt": "2026-08-26T07:32:58.331473+00:00",
    "archiveCaptureTimestamp": null,
    "sha256": "95346216fd20465452e6c006dfd47cb61f399eeed250f772c9a591792534a1a8",
    "provenance": "live-official",
    "encoding": "windows-1251",
    "extractionMethod": "randomized-inline-javascript-direct-protocol",
    "derivation": "direct",
    "hierarchyEvidence": {
      "path": "sha256/77/77ca71997e13188d8dfd931bb0822142a36daee4263c818c1c24fc9b8b9b16fc",
      "sha256": "77ca71997e13188d8dfd931bb0822142a36daee4263c818c1c24fc9b8b9b16fc"
    }
  }
} satisfies HistoricalUikProtocol;
