// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2016_districts_region_48 = [
  {
    "election": "2016-duma",
    "districtNumber": 114,
    "oikTvd": "100100067796005",
    "oikName": "Липецкая область – Липецкий",
    "regionCode": "48",
    "regionTvd": "100100067796004",
    "regionName": "Липецкая область",
    "winnerCandidateVibid": "2482000589186",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2482000589186",
        "candidateVibid": "2482000589186",
        "fullName": "Борцов Николай Иванович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:2482000600477",
        "candidateVibid": "2482000600477",
        "fullName": "Валетов Сергей Анатольевич",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000603368",
        "candidateVibid": "2482000603368",
        "fullName": "Еркина Елена Викторовна",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000600403",
        "candidateVibid": "2482000600403",
        "fullName": "Ковригин Вадим Валерьевич",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000586347",
        "candidateVibid": "2482000586347",
        "fullName": "Разворотнев Николай Васильевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000591037",
        "candidateVibid": "2482000591037",
        "fullName": "Трофимов Вадим Юрьевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000600784",
        "candidateVibid": "2482000600784",
        "fullName": "Тюнина Светлана Валерьевна",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000600511",
        "candidateVibid": "2482000600511",
        "fullName": "Фомичев Владимир Николаевич",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000588997",
        "candidateVibid": "2482000588997",
        "fullName": "Халимончук Максим Валентинович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/lipetsk?action=show&root=1000151&tvd=100100067796005&vrn=100100067795849&region=48&global=null&sub_region=48&prver=0&pronetvd=null&vibid=100100067796005&type=463",
        "sha256": "fcdab96fd95e89ae3a7c662c696d36b72218c68c069e4d5053effa0399f910d5",
        "retrievedAt": "2026-08-28T07:42:21.794146+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/lipetsk?action=show&root=1000151&tvd=100100067796005&vrn=100100067795849&region=48&global=null&sub_region=48&prver=0&pronetvd=null&vibid=100100067796005&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 130520,
        "summedTikWinnerVoteTotal": 130520
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 115,
    "oikTvd": "100100067796006",
    "oikName": "Липецкая область – Левобережный",
    "regionCode": "48",
    "regionTvd": "100100067796004",
    "regionName": "Липецкая область",
    "winnerCandidateVibid": "2482000601951",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2482000590623",
        "candidateVibid": "2482000590623",
        "fullName": "Ксенофонтова Лариса Васильевна",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000600384",
        "candidateVibid": "2482000600384",
        "fullName": "Рожнов Евгений Вячеславович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000601951",
        "candidateVibid": "2482000601951",
        "fullName": "Тарасенко Михаил Васильевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:2482000586372",
        "candidateVibid": "2482000586372",
        "fullName": "Токарев Сергей Владимирович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000600369",
        "candidateVibid": "2482000600369",
        "fullName": "Трофимов Александр Вадимович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2482000580315",
        "candidateVibid": "2482000580315",
        "fullName": "Хомутинников Олег Георгиевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/lipetsk?action=show&root=1000152&tvd=100100067796006&vrn=100100067795849&region=48&global=null&sub_region=48&prver=0&pronetvd=null&vibid=100100067796006&type=463",
        "sha256": "6f9407f987e236dd4a5342b42bc695d48e9f8588ab7cd1c556faa89dac12614e",
        "retrievedAt": "2026-08-28T07:42:21.961426+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/lipetsk?action=show&root=1000152&tvd=100100067796006&vrn=100100067795849&region=48&global=null&sub_region=48&prver=0&pronetvd=null&vibid=100100067796006&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 154786,
        "summedTikWinnerVoteTotal": 154786
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
