// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2016_districts_region_16 = [
  {
    "election": "2016-duma",
    "districtNumber": 26,
    "oikTvd": "100100067795893",
    "oikName": "Республика Татарстан (Татарстан) – Приволжский",
    "regionCode": "16",
    "regionTvd": "100100067795892",
    "regionName": "Республика Татарстан (Татарстан)",
    "winnerCandidateVibid": "4164026236678",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:4164026236267",
        "candidateVibid": "4164026236267",
        "fullName": "Бердников Дмитрий Николаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026236433",
        "candidateVibid": "4164026236433",
        "fullName": "Бильгильдеева Рушания Габдулахатовна",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026236947",
        "candidateVibid": "4164026236947",
        "fullName": "Бородин Евгений Анатольевич",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026218595",
        "candidateVibid": "4164026218595",
        "fullName": "Габдуллин Ленар Айдарович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026218539",
        "candidateVibid": "4164026218539",
        "fullName": "Галяутдинова Лилия Рашитовна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026237005",
        "candidateVibid": "4164026237005",
        "fullName": "Муртазин Ирек Минзакиевич",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "выбывший (после регистрации) кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026236487",
        "candidateVibid": "4164026236487",
        "fullName": "Новиков Дмитрий Николаевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026236594",
        "candidateVibid": "4164026236594",
        "fullName": "Новиков Илья Вадимович",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026237830",
        "candidateVibid": "4164026237830",
        "fullName": "Пешков Виктор Петрович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026217729",
        "candidateVibid": "4164026217729",
        "fullName": "Сальников Сергей Викторович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164026236678",
        "candidateVibid": "4164026236678",
        "fullName": "Сибагатуллин Фатих Саубанович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000039&tvd=100100067795893&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795893&type=463",
        "sha256": "e836c98cc103d3910bf458424491c8325d798f0c7a6d91004d1b6003c103a79e",
        "retrievedAt": "2026-08-28T07:42:04.816829+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000039&tvd=100100067795893&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795893&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 248549,
        "summedTikWinnerVoteTotal": 248549
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 27,
    "oikTvd": "100100067795894",
    "oikName": "Республика Татарстан (Татарстан) – Московский",
    "regionCode": "16",
    "regionTvd": "100100067795892",
    "regionName": "Республика Татарстан (Татарстан)",
    "winnerCandidateVibid": "4164024172579",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:4164024172315",
        "candidateVibid": "4164024172315",
        "fullName": "Бердников Дмитрий Николаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164024172579",
        "candidateVibid": "4164024172579",
        "fullName": "Гильмутдинов Ильдар Ирекович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:4164024172476",
        "candidateVibid": "4164024172476",
        "fullName": "Карымов Дмитрий Юрьевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164024172372",
        "candidateVibid": "4164024172372",
        "fullName": "Кудряшов Андрей Витальевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164024172893",
        "candidateVibid": "4164024172893",
        "fullName": "Кукоба Людмила Сергеевна",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164024172925",
        "candidateVibid": "4164024172925",
        "fullName": "Миргалимов Хафиз Гаязович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164024172699",
        "candidateVibid": "4164024172699",
        "fullName": "Рамазанов Рустам Габтилфаритович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164024172747",
        "candidateVibid": "4164024172747",
        "fullName": "Шамсутдинов Марсель Дикаянович",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000040&tvd=100100067795894&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795894&type=463",
        "sha256": "a068f75d23ad6aa461c4d3e0b66fe311c774ab58f1b5803305c563d40d7c5767",
        "retrievedAt": "2026-08-28T07:42:04.940744+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000040&tvd=100100067795894&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795894&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 311863,
        "summedTikWinnerVoteTotal": 311863
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 28,
    "oikTvd": "100100067795895",
    "oikName": "Республика Татарстан (Татарстан) – Нижнекамский",
    "regionCode": "16",
    "regionTvd": "100100067795892",
    "regionName": "Республика Татарстан (Татарстан)",
    "winnerCandidateVibid": "4164038200764",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:4164038200292",
        "candidateVibid": "4164038200292",
        "fullName": "Артемьева Анна Владимировна",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164038200879",
        "candidateVibid": "4164038200879",
        "fullName": "Баканач Олег Васильевич",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164038200488",
        "candidateVibid": "4164038200488",
        "fullName": "Вильданов Дамир Насырович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164038200318",
        "candidateVibid": "4164038200318",
        "fullName": "Закиров Ринат Замильевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164038200535",
        "candidateVibid": "4164038200535",
        "fullName": "Иосипов Евгений Константинович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164038200618",
        "candidateVibid": "4164038200618",
        "fullName": "Лукин Андрей Михайлович",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164038200764",
        "candidateVibid": "4164038200764",
        "fullName": "Хайруллин Айрат Назипович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:4164038200659",
        "candidateVibid": "4164038200659",
        "fullName": "Ягудин Альберт Ахметвагизович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000041&tvd=100100067795895&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795895&type=463",
        "sha256": "e27a925a06ab9f281abd01e39a65788e0f0b767fd96a0d9c46ac77badaa57d27",
        "retrievedAt": "2026-08-28T07:42:05.347841+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000041&tvd=100100067795895&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795895&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 353675,
        "summedTikWinnerVoteTotal": 353675
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 29,
    "oikTvd": "100100067795896",
    "oikName": "Республика Татарстан (Татарстан) – Набережно-Челнинский",
    "regionCode": "16",
    "regionTvd": "100100067795892",
    "regionName": "Республика Татарстан (Татарстан)",
    "winnerCandidateVibid": "4164037183563",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:4164037183400",
        "candidateVibid": "4164037183400",
        "fullName": "Абдулов Рамиль Эминович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164037183344",
        "candidateVibid": "4164037183344",
        "fullName": "Байрамов Рафаэль Рахматуллович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164037183574",
        "candidateVibid": "4164037183574",
        "fullName": "Гарифуллин Мансур Зайдуллович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164037183325",
        "candidateVibid": "4164037183325",
        "fullName": "Гурьева Татьяна Ивановна",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164037183267",
        "candidateVibid": "4164037183267",
        "fullName": "Ершов Владимир Константинович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164037183563",
        "candidateVibid": "4164037183563",
        "fullName": "Когогина Альфия Гумаровна",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:4164037183509",
        "candidateVibid": "4164037183509",
        "fullName": "Мингалимов Рузиль Галиевич",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164037183477",
        "candidateVibid": "4164037183477",
        "fullName": "Нурутдинов Рафаил Фаттахович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164037183283",
        "candidateVibid": "4164037183283",
        "fullName": "Павперова Ирина Юрьевна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164037168543",
        "candidateVibid": "4164037168543",
        "fullName": "Украев Олег Альбертович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000042&tvd=100100067795896&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795896&type=463",
        "sha256": "66d3364c44ac1cb506386ebfb4592e3af1f066acc1b8711279487b068bd630aa",
        "retrievedAt": "2026-08-28T07:42:05.743265+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000042&tvd=100100067795896&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795896&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 316091,
        "summedTikWinnerVoteTotal": 316091
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 30,
    "oikTvd": "100100067795897",
    "oikName": "Республика Татарстан (Татарстан) – Альметьевский",
    "regionCode": "16",
    "regionTvd": "100100067795892",
    "regionName": "Республика Татарстан (Татарстан)",
    "winnerCandidateVibid": "4164007182091",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:4164007182364",
        "candidateVibid": "4164007182364",
        "fullName": "Агафонов Александр Федорович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164007181332",
        "candidateVibid": "4164007181332",
        "fullName": "Алейников Валерий Вячеславович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164007182264",
        "candidateVibid": "4164007182264",
        "fullName": "Курбанов Марат Асгатович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164007182131",
        "candidateVibid": "4164007182131",
        "fullName": "Мингазов Закарий Ильясович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164007182013",
        "candidateVibid": "4164007182013",
        "fullName": "Мухаметшин Эдуард Закирович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164007182091",
        "candidateVibid": "4164007182091",
        "fullName": "Хайров Ринат Шамильевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:4164007182199",
        "candidateVibid": "4164007182199",
        "fullName": "Ханипов Айрат Раисович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000043&tvd=100100067795897&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795897&type=463",
        "sha256": "88f7975505789be57283a50bbb5d4ae8f34c8db5361791bc02d4491e65d5d7bc",
        "retrievedAt": "2026-08-28T07:42:05.767763+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000043&tvd=100100067795897&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795897&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 307016,
        "summedTikWinnerVoteTotal": 307016
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 31,
    "oikTvd": "100100067795898",
    "oikName": "Республика Татарстан (Татарстан) – Центральный",
    "regionCode": "16",
    "regionTvd": "100100067795892",
    "regionName": "Республика Татарстан (Татарстан)",
    "winnerCandidateVibid": "4164025210015",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:4164025209573",
        "candidateVibid": "4164025209573",
        "fullName": "Бердников Дмитрий Николаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164025209682",
        "candidateVibid": "4164025209682",
        "fullName": "Валиев Альфред Ракибович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164025209497",
        "candidateVibid": "4164025209497",
        "fullName": "Габдрахманов Марсель Маликович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164025210097",
        "candidateVibid": "4164025210097",
        "fullName": "Зинатуллин Руслан Мансурович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164025210266",
        "candidateVibid": "4164025210266",
        "fullName": "Кротов Максим Сергеевич",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164025210015",
        "candidateVibid": "4164025210015",
        "fullName": "Минкин Иршат Султанович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:4164025210003",
        "candidateVibid": "4164025210003",
        "fullName": "Прокофьев Артём Вячеславович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164025209936",
        "candidateVibid": "4164025209936",
        "fullName": "Файзуллина Айгуль Рашитовна",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4164025189174",
        "candidateVibid": "4164025189174",
        "fullName": "Халиуллин Руслан Рустамович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000044&tvd=100100067795898&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795898&type=463",
        "sha256": "4d8381b8c7ca572b5ace0e9201cf6ec47a74faa0c26e1551c18e44ec65bc2b7f",
        "retrievedAt": "2026-08-28T07:42:05.980603+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/tatarstan?action=show&root=1000044&tvd=100100067795898&vrn=100100067795849&region=16&global=null&sub_region=16&prver=0&pronetvd=null&vibid=100100067795898&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 180244,
        "summedTikWinnerVoteTotal": 180244
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
