// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2016_districts_region_37 = [
  {
    "election": "2016-duma",
    "districtNumber": 91,
    "oikTvd": "100100067795972",
    "oikName": "Ивановская область – Ивановский",
    "regionCode": "37",
    "regionTvd": "100100067795971",
    "regionName": "Ивановская область",
    "winnerCandidateVibid": "2372000907917",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2372000908324",
        "candidateVibid": "2372000908324",
        "fullName": "Астафьев Роман Дмитриевич",
        "nominatingEntity": "Политическая партия \"Гражданская Платформа\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000908226",
        "candidateVibid": "2372000908226",
        "fullName": "Бедяев Данила Сергеевич",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000908525",
        "candidateVibid": "2372000908525",
        "fullName": "Даричева Ольга Алексеевна",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000908248",
        "candidateVibid": "2372000908248",
        "fullName": "Калинин Вячеслав Вячеславович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000907812",
        "candidateVibid": "2372000907812",
        "fullName": "Курин Владимир Геннадьевич",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000906676",
        "candidateVibid": "2372000906676",
        "fullName": "Орехов Александр Станиславович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000908867",
        "candidateVibid": "2372000908867",
        "fullName": "Попов Павел Вениаминович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000906687",
        "candidateVibid": "2372000906687",
        "fullName": "Саломатин Дмитрий Эдуардович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000907917",
        "candidateVibid": "2372000907917",
        "fullName": "Хохлов Алексей Алексеевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:2372000880620",
        "candidateVibid": "2372000880620",
        "fullName": "Шелякин Дмитрий Викторович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/ivanovo?action=show&root=1000118&tvd=100100067795972&vrn=100100067795849&region=37&global=null&sub_region=37&prver=0&pronetvd=null&vibid=100100067795972&type=463",
        "sha256": "53bc98243f473b6156b95b41540791f1dafbc47e8ef6aa24612dc8fed327096c",
        "retrievedAt": "2026-08-28T07:42:17.933416+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/ivanovo?action=show&root=1000118&tvd=100100067795972&vrn=100100067795849&region=37&global=null&sub_region=37&prver=0&pronetvd=null&vibid=100100067795972&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 68291,
        "summedTikWinnerVoteTotal": 68291
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 92,
    "oikTvd": "100100067795973",
    "oikName": "Ивановская область – Кинешемский",
    "regionCode": "37",
    "regionTvd": "100100067795971",
    "regionName": "Ивановская область",
    "winnerCandidateVibid": "2372000908343",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2372000907850",
        "candidateVibid": "2372000907850",
        "fullName": "Вальков Андрей Юрьевич",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000880631",
        "candidateVibid": "2372000880631",
        "fullName": "Верясов Максим Петрович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000908298",
        "candidateVibid": "2372000908298",
        "fullName": "Ганенко Юрий Петрович",
        "nominatingEntity": "Политическая партия \"Гражданская Платформа\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000906698",
        "candidateVibid": "2372000906698",
        "fullName": "Кленов Владимир Витальевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000907031",
        "candidateVibid": "2372000907031",
        "fullName": "Кузьменко Виктор Николаевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000908205",
        "candidateVibid": "2372000908205",
        "fullName": "Мельников Иван Юрьевич",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000906709",
        "candidateVibid": "2372000906709",
        "fullName": "Сивохин Дмитрий Владимирович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2372000908343",
        "candidateVibid": "2372000908343",
        "fullName": "Смирнов Юрий Валентинович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/ivanovo?action=show&root=1000119&tvd=100100067795973&vrn=100100067795849&region=37&global=null&sub_region=37&prver=0&pronetvd=null&vibid=100100067795973&type=463",
        "sha256": "c662ad1bc218c86c535feb37e7c4cd4065261d54c24c4d8cb7727022c2591bda",
        "retrievedAt": "2026-08-28T07:42:18.014410+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/ivanovo?action=show&root=1000119&tvd=100100067795973&vrn=100100067795849&region=37&global=null&sub_region=37&prver=0&pronetvd=null&vibid=100100067795973&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 56666,
        "summedTikWinnerVoteTotal": 56666
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
