// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2016_districts_region_93 = [
  {
    "election": "2016-duma",
    "districtNumber": 19,
    "oikTvd": "100100067796160",
    "oikName": "Республика Крым – Симферопольский",
    "regionCode": "93",
    "regionTvd": "100100067796159",
    "regionName": "Республика Крым",
    "winnerCandidateVibid": "493402186610",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:493402187220",
        "candidateVibid": "493402187220",
        "fullName": "Абдувалиев Таир Аметович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186725",
        "candidateVibid": "493402186725",
        "fullName": "Азардович Анатолий Анатольевич",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186124",
        "candidateVibid": "493402186124",
        "fullName": "Акимов Сергей Владимирович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186030",
        "candidateVibid": "493402186030",
        "fullName": "Арифов Мустафа Ягьяевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186159",
        "candidateVibid": "493402186159",
        "fullName": "Баклан Владимир Витальевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186172",
        "candidateVibid": "493402186172",
        "fullName": "Боиштян Александр Павлович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186702",
        "candidateVibid": "493402186702",
        "fullName": "Грицак Елена Валерьевна",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186896",
        "candidateVibid": "493402186896",
        "fullName": "Каверина Елена Владимировна",
        "nominatingEntity": "Общественная организация - Политическая партия \"ПАРТИЯ РОДИТЕЛЕЙ БУДУЩЕГО\"",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186099",
        "candidateVibid": "493402186099",
        "fullName": "Кириллов Владимир Игоревич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186056",
        "candidateVibid": "493402186056",
        "fullName": "Климчук Олег Алексеевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186610",
        "candidateVibid": "493402186610",
        "fullName": "Козенко Андрей Дмитриевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:493402185959",
        "candidateVibid": "493402185959",
        "fullName": "Марченко Евгений Михайлович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186068",
        "candidateVibid": "493402186068",
        "fullName": "Петров Анатолий Иванович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402187268",
        "candidateVibid": "493402187268",
        "fullName": "Салихова Резеда Радиковна",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402187486",
        "candidateVibid": "493402187486",
        "fullName": "Талипов Александр Валериевич",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402187159",
        "candidateVibid": "493402187159",
        "fullName": "Ханин Николай Александрович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186390",
        "candidateVibid": "493402186390",
        "fullName": "Чернышев Александр Иванович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493402186085",
        "candidateVibid": "493402186085",
        "fullName": "Шефердекер Вадим Владимирович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/crimea?action=show&root=1000306&tvd=100100067796160&vrn=100100067795849&region=93&global=null&sub_region=93&prver=0&pronetvd=null&vibid=100100067796160&type=463",
        "sha256": "e764927c37079a5d7dd8667bb9a5e84ebc61a35b8e904845dc4d35b60acafd79",
        "retrievedAt": "2026-08-28T07:42:03.287511+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/crimea?action=show&root=1000306&tvd=100100067796160&vrn=100100067795849&region=93&global=null&sub_region=93&prver=0&pronetvd=null&vibid=100100067796160&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 137938,
        "summedTikWinnerVoteTotal": 137938
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 20,
    "oikTvd": "100100067796161",
    "oikName": "Республика Крым – Керченский",
    "regionCode": "93",
    "regionTvd": "100100067796159",
    "regionName": "Республика Крым",
    "winnerCandidateVibid": "4934014106995",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:4934014106983",
        "candidateVibid": "4934014106983",
        "fullName": "Алексеев Валерий Викторович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4934014106995",
        "candidateVibid": "4934014106995",
        "fullName": "Бахарев Константин Михайлович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:4934014107127",
        "candidateVibid": "4934014107127",
        "fullName": "Воропай Михаил Викторович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4934014106464",
        "candidateVibid": "4934014106464",
        "fullName": "Кийко Игорь Александрович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4934014106702",
        "candidateVibid": "4934014106702",
        "fullName": "Кискин Степан Степанович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4934014106827",
        "candidateVibid": "4934014106827",
        "fullName": "Паша Андрей Викторович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4934014107022",
        "candidateVibid": "4934014107022",
        "fullName": "Першиков Юрий Александрович",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4934014106933",
        "candidateVibid": "4934014106933",
        "fullName": "Свистунов Александр Григорьевич",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:4934014106911",
        "candidateVibid": "4934014106911",
        "fullName": "Эмиров Рустем",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/crimea?action=show&root=1000307&tvd=100100067796161&vrn=100100067795849&region=93&global=null&sub_region=93&prver=0&pronetvd=null&vibid=100100067796161&type=463",
        "sha256": "b3ec1fa053315a5736895e5e455ffc87d694cf4642228f3b6d1f0b826240f18e",
        "retrievedAt": "2026-08-28T07:42:03.352239+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/crimea?action=show&root=1000307&tvd=100100067796161&vrn=100100067795849&region=93&global=null&sub_region=93&prver=0&pronetvd=null&vibid=100100067796161&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 167896,
        "summedTikWinnerVoteTotal": 167896
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 21,
    "oikTvd": "100100067796162",
    "oikName": "Республика Крым – Евпаторийский",
    "regionCode": "93",
    "regionTvd": "100100067796159",
    "regionName": "Республика Крым",
    "winnerCandidateVibid": "493400789970",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:493400789838",
        "candidateVibid": "493400789838",
        "fullName": "Беккер Олег Ефимович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493400789985",
        "candidateVibid": "493400789985",
        "fullName": "Боушев Владимир Геннадьевич",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493400790072",
        "candidateVibid": "493400790072",
        "fullName": "Воронова Марина Владимировна",
        "nominatingEntity": "Общественная организация - Политическая партия \"ПАРТИЯ РОДИТЕЛЕЙ БУДУЩЕГО\"",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493400790200",
        "candidateVibid": "493400790200",
        "fullName": "Лебедева Наталья Николаевна",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493400789970",
        "candidateVibid": "493400789970",
        "fullName": "Савченко Светлана Борисовна",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:493400790187",
        "candidateVibid": "493400790187",
        "fullName": "Силиверстов Игорь Витальевич",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493400789816",
        "candidateVibid": "493400789816",
        "fullName": "Соломахин Олег Андреевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493400790106",
        "candidateVibid": "493400790106",
        "fullName": "Тарасов Валерий Иванович",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493400789642",
        "candidateVibid": "493400789642",
        "fullName": "Шперов Павел Валентинович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:493400789940",
        "candidateVibid": "493400789940",
        "fullName": "Шуба Дмитрий Евгеньевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/crimea?action=show&root=1000308&tvd=100100067796162&vrn=100100067795849&region=93&global=null&sub_region=93&prver=0&pronetvd=null&vibid=100100067796162&type=463",
        "sha256": "0af3a00b2b8fbc00150b03b309fd4e82134987c4719db2929e43ae683faf275c",
        "retrievedAt": "2026-08-28T07:42:03.479169+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/crimea?action=show&root=1000308&tvd=100100067796162&vrn=100100067795849&region=93&global=null&sub_region=93&prver=0&pronetvd=null&vibid=100100067796162&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 189624,
        "summedTikWinnerVoteTotal": 189624
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
