// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2016_districts_region_55 = [
  {
    "election": "2016-duma",
    "districtNumber": 139,
    "oikTvd": "100100067796037",
    "oikName": "Омская область – Омский",
    "regionCode": "55",
    "regionTvd": "100100067796036",
    "regionName": "Омская область",
    "winnerCandidateVibid": "2552000989906",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2552000987412",
        "candidateVibid": "2552000987412",
        "fullName": "Алехин Андрей Анатольевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000996065",
        "candidateVibid": "2552000996065",
        "fullName": "Артемьев Николай Викторович",
        "nominatingEntity": "Политическая партия \"Гражданская Платформа\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000989917",
        "candidateVibid": "2552000989917",
        "fullName": "Барков Александр Валерьевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000990457",
        "candidateVibid": "2552000990457",
        "fullName": "Басов Игорь Геннадьевич",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000985457",
        "candidateVibid": "2552000985457",
        "fullName": "Горовцов Дмитрий Евгеньевич",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000994894",
        "candidateVibid": "2552000994894",
        "fullName": "Еременко Татьяна Анатольевна",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000982997",
        "candidateVibid": "2552000982997",
        "fullName": "Клепиков Алексей Анатольевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000992038",
        "candidateVibid": "2552000992038",
        "fullName": "Костарев Сергей Владимирович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000989906",
        "candidateVibid": "2552000989906",
        "fullName": "Шрейдер Виктор Филиппович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000183&tvd=100100067796037&vrn=100100067795849&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100067796037&type=463",
        "sha256": "224b15c94215eb3b7a709513dc21eed086243a4cc8d8f24fca3e8276fc1ea751",
        "retrievedAt": "2026-08-28T07:42:25.944692+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000183&tvd=100100067796037&vrn=100100067795849&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100067796037&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 57552,
        "summedTikWinnerVoteTotal": 57552
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 140,
    "oikTvd": "100100067796038",
    "oikName": "Омская область – Москаленский",
    "regionCode": "55",
    "regionTvd": "100100067796036",
    "regionName": "Омская область",
    "winnerCandidateVibid": "2552000987306",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2552000990097",
        "candidateVibid": "2552000990097",
        "fullName": "Асташенко Сергей Дмитриевич",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000982914",
        "candidateVibid": "2552000982914",
        "fullName": "Атаманиченко Кирилл Игоревич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000983272",
        "candidateVibid": "2552000983272",
        "fullName": "Григорьева Алеся Викторовна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000987491",
        "candidateVibid": "2552000987491",
        "fullName": "Дубовский Евгений Юрьевич",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000989928",
        "candidateVibid": "2552000989928",
        "fullName": "Жуков Владимир Алексеевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000995699",
        "candidateVibid": "2552000995699",
        "fullName": "Курнявко Олег Леонидович",
        "nominatingEntity": "Политическая партия \"Гражданская Платформа\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000995804",
        "candidateVibid": "2552000995804",
        "fullName": "Огаркова Татьяна Михайловна",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000987306",
        "candidateVibid": "2552000987306",
        "fullName": "Смолин Олег Николаевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:2552000900285",
        "candidateVibid": "2552000900285",
        "fullName": "Хасанов Мухаметкали",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000184&tvd=100100067796038&vrn=100100067795849&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100067796038&type=463",
        "sha256": "e70e49dc68397baeea09b205f427250866c0ce1018938428b106ebb65babe3dd",
        "retrievedAt": "2026-08-28T07:42:26.084945+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000184&tvd=100100067796038&vrn=100100067795849&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100067796038&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 87848,
        "summedTikWinnerVoteTotal": 87848
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 141,
    "oikTvd": "100100067796039",
    "oikName": "Омская область – Любинский",
    "regionCode": "55",
    "regionTvd": "100100067796036",
    "regionName": "Омская область",
    "winnerCandidateVibid": "2552000990468",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2552000990706",
        "candidateVibid": "2552000990706",
        "fullName": "Аргат Ольга Владимировна",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000990468",
        "candidateVibid": "2552000990468",
        "fullName": "Голушко Андрей Иванович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:2552000994508",
        "candidateVibid": "2552000994508",
        "fullName": "Денисенко Олег Иванович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000995687",
        "candidateVibid": "2552000995687",
        "fullName": "Колесников Олег Юрьевич",
        "nominatingEntity": "Политическая партия \"Гражданская Платформа\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000995793",
        "candidateVibid": "2552000995793",
        "fullName": "Кочетков Сергей Петрович",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000987502",
        "candidateVibid": "2552000987502",
        "fullName": "Кравцов Александр Владимирович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000942083",
        "candidateVibid": "2552000942083",
        "fullName": "Кривошеев Юрий Вячеславович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000983027",
        "candidateVibid": "2552000983027",
        "fullName": "Ложкин Алексей Николаевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000992049",
        "candidateVibid": "2552000992049",
        "fullName": "Мельников Борис Викторович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000989939",
        "candidateVibid": "2552000989939",
        "fullName": "Подзоров Александр Георгиевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000898648",
        "candidateVibid": "2552000898648",
        "fullName": "Рубанова Елена Владимировна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000984855",
        "candidateVibid": "2552000984855",
        "fullName": "Селезнев Виктор Владимирович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2552000995754",
        "candidateVibid": "2552000995754",
        "fullName": "Якименко Алексей Евгеньевич",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000185&tvd=100100067796039&vrn=100100067795849&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100067796039&type=463",
        "sha256": "48fba71207d787bd653a8058a967f9e2937fd7031ad97c6ad5e9bc344d4307a0",
        "retrievedAt": "2026-08-28T07:42:26.221363+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000185&tvd=100100067796039&vrn=100100067795849&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100067796039&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 92684,
        "summedTikWinnerVoteTotal": 92684
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
