// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2016_districts_region_56 = [
  {
    "election": "2016-duma",
    "districtNumber": 142,
    "oikTvd": "100100067796041",
    "oikName": "Оренбургская область – Оренбургский",
    "regionCode": "56",
    "regionTvd": "100100067796040",
    "regionName": "Оренбургская область",
    "winnerCandidateVibid": "25620001003464",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2562000994789",
        "candidateVibid": "2562000994789",
        "fullName": "Амелин Максим Анатольевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2562000994542",
        "candidateVibid": "2562000994542",
        "fullName": "Деденев Алексей Анатольевич",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ ВЕЛИКОЕ ОТЕЧЕСТВО\"",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001003788",
        "candidateVibid": "25620001003788",
        "fullName": "Калинин Александр Владимирович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2562000991818",
        "candidateVibid": "2562000991818",
        "fullName": "Карпов Александр Николаевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001003464",
        "candidateVibid": "25620001003464",
        "fullName": "Мищеряков Юрий Николаевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:25620001005325",
        "candidateVibid": "25620001005325",
        "fullName": "Рычагов Антон Владимирович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004283",
        "candidateVibid": "25620001004283",
        "fullName": "Столпак Сергей Павлович",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001005338",
        "candidateVibid": "25620001005338",
        "fullName": "Тишин Владимир Владимирович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004865",
        "candidateVibid": "25620001004865",
        "fullName": "Фомин Сергей Александрович",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2562000994730",
        "candidateVibid": "2562000994730",
        "fullName": "Фролов Владимир Иванович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001003230",
        "candidateVibid": "25620001003230",
        "fullName": "Химич Сергей Александрович",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001005656",
        "candidateVibid": "25620001005656",
        "fullName": "Шишков Евгений Владимирович",
        "nominatingEntity": "Общественная организация - Политическая партия \"ПАРТИЯ РОДИТЕЛЕЙ БУДУЩЕГО\"",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/orenburg?action=show&root=1000187&tvd=100100067796041&vrn=100100067795849&region=56&global=null&sub_region=56&prver=0&pronetvd=null&vibid=100100067796041&type=463",
        "sha256": "dbcb2555e23bfd7a9cc49a68307c244c00c09943b9b27132d517286af8dce636",
        "retrievedAt": "2026-08-28T07:42:26.549777+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/orenburg?action=show&root=1000187&tvd=100100067796041&vrn=100100067795849&region=56&global=null&sub_region=56&prver=0&pronetvd=null&vibid=100100067796041&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 92564,
        "summedTikWinnerVoteTotal": 92564
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 143,
    "oikTvd": "100100067796042",
    "oikName": "Оренбургская область – Бугурусланский",
    "regionCode": "56",
    "regionTvd": "100100067796040",
    "regionName": "Оренбургская область",
    "winnerCandidateVibid": "25620001003807",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:25620001004303",
        "candidateVibid": "25620001004303",
        "fullName": "Асяев Фаик Инсафович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004760",
        "candidateVibid": "25620001004760",
        "fullName": "Головина Татьяна Александровна",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2562000991769",
        "candidateVibid": "2562000991769",
        "fullName": "Катасонов Сергей Михайлович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004637",
        "candidateVibid": "25620001004637",
        "fullName": "Климова Ирина Александровна",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004626",
        "candidateVibid": "25620001004626",
        "fullName": "Лазаров Георги Атанасов",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004382",
        "candidateVibid": "25620001004382",
        "fullName": "Мунжасаров Нурлан Нурмагамбетович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001003807",
        "candidateVibid": "25620001003807",
        "fullName": "Сухарев Игорь Николаевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true,
        "registryIsElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004748",
        "candidateVibid": "25620001004748",
        "fullName": "Туршинов Дидар Саулебаевич",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001001594",
        "candidateVibid": "25620001001594",
        "fullName": "Уралов Семен Сергеевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2562000997696",
        "candidateVibid": "2562000997696",
        "fullName": "Щепинов Максим Александрович",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/orenburg?action=show&root=1000188&tvd=100100067796042&vrn=100100067795849&region=56&global=null&sub_region=56&prver=0&pronetvd=null&vibid=100100067796042&type=463",
        "sha256": "e957a62f646f549753b0a74d88394f1c997cd4d88a641b8b4a2c4be036528d76",
        "retrievedAt": "2026-08-28T07:42:26.706581+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/orenburg?action=show&root=1000188&tvd=100100067796042&vrn=100100067795849&region=56&global=null&sub_region=56&prver=0&pronetvd=null&vibid=100100067796042&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 100425,
        "summedTikWinnerVoteTotal": 100425
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 144,
    "oikTvd": "100100067796043",
    "oikName": "Оренбургская область – Орский",
    "regionCode": "56",
    "regionTvd": "100100067796040",
    "regionName": "Оренбургская область",
    "winnerCandidateVibid": "25620001003253",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:25620001003279",
        "candidateVibid": "25620001003279",
        "fullName": "Бенцман Сергей Исакович",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001003253",
        "candidateVibid": "25620001003253",
        "fullName": "Заварзин Виктор Михайлович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004243",
        "candidateVibid": "25620001004243",
        "fullName": "Иванов Александр Анатольевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004691",
        "candidateVibid": "25620001004691",
        "fullName": "Исмагилов Руслан Шавкатович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2562000994510",
        "candidateVibid": "2562000994510",
        "fullName": "Кулахметов Кайрат Жайгунусович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2562000991851",
        "candidateVibid": "2562000991851",
        "fullName": "Мирохин Владимир Юрьевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004219",
        "candidateVibid": "25620001004219",
        "fullName": "Нетесанов Сергей Дмитриевич",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:25620001004707",
        "candidateVibid": "25620001004707",
        "fullName": "Рыбалко Ольга Александровна",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/orenburg?action=show&root=1000189&tvd=100100067796043&vrn=100100067795849&region=56&global=null&sub_region=56&prver=0&pronetvd=null&vibid=100100067796043&type=463",
        "sha256": "dbb6f58baed7f10299d985993f5dc0c6e9c5d1ee5a4fc87d01d4ef24c1c279cb",
        "retrievedAt": "2026-08-28T07:42:26.815167+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/orenburg?action=show&root=1000189&tvd=100100067796043&vrn=100100067795849&region=56&global=null&sub_region=56&prver=0&pronetvd=null&vibid=100100067796043&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 86334,
        "summedTikWinnerVoteTotal": 86334
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
