// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2016_districts_region_24 = [
  {
    "election": "2016-duma",
    "districtNumber": 54,
    "oikTvd": "100100067795926",
    "oikName": "Красноярский край – Красноярский",
    "regionCode": "24",
    "regionTvd": "100100067795925",
    "regionName": "Красноярский край",
    "winnerCandidateVibid": "22420001396432",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:22420001387054",
        "candidateVibid": "22420001387054",
        "fullName": "Владимиров Владимир Владимирович",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001400620",
        "candidateVibid": "22420001400620",
        "fullName": "Горностаев Александр Сергеевич",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001395003",
        "candidateVibid": "22420001395003",
        "fullName": "Зберовский Андрей Викторович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001389141",
        "candidateVibid": "22420001389141",
        "fullName": "Осипова Татьяна Юрьевна",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001399759",
        "candidateVibid": "22420001399759",
        "fullName": "Слонов Алексей Павлович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001398755",
        "candidateVibid": "22420001398755",
        "fullName": "Тарасов Артем Михайлович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001258110",
        "candidateVibid": "22420001258110",
        "fullName": "Титов Сергей Сергеевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001397813",
        "candidateVibid": "22420001397813",
        "fullName": "Шахматов Сергей Александрович",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001396432",
        "candidateVibid": "22420001396432",
        "fullName": "Швыткин Юрий Николаевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/krasnoyarsk?action=show&root=1000072&tvd=100100067795926&vrn=100100067795849&region=24&global=null&sub_region=24&prver=0&pronetvd=null&vibid=100100067795926&type=463",
        "sha256": "ed7c9840ce33d07f148039feeec2c97a521b14eee9c6afebbb3ac08cdda84cee",
        "retrievedAt": "2026-08-28T07:42:11.504737+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/krasnoyarsk?action=show&root=1000072&tvd=100100067795926&vrn=100100067795849&region=24&global=null&sub_region=24&prver=0&pronetvd=null&vibid=100100067795926&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 83257,
        "summedTikWinnerVoteTotal": 83257
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 55,
    "oikTvd": "100100067795927",
    "oikName": "Красноярский край – Центральный",
    "regionCode": "24",
    "regionTvd": "100100067795925",
    "regionName": "Красноярский край",
    "winnerCandidateVibid": "22420001399915",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:22420001396268",
        "candidateVibid": "22420001396268",
        "fullName": "Бабурин Евгений Алексеевич",
        "nominatingEntity": "Политическая партия \"Партия народной свободы\" (ПАРНАС)",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001395285",
        "candidateVibid": "22420001395285",
        "fullName": "Вычужанин Петр Владимирович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001258122",
        "candidateVibid": "22420001258122",
        "fullName": "Глисков Александр Александрович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001389155",
        "candidateVibid": "22420001389155",
        "fullName": "Гуров Антон Владимирович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001395014",
        "candidateVibid": "22420001395014",
        "fullName": "Маркерт Максим Андреевич",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001321444",
        "candidateVibid": "22420001321444",
        "fullName": "Моисеев Пётр Александрович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001259046",
        "candidateVibid": "22420001259046",
        "fullName": "Патраков Владислав Владимирович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001399915",
        "candidateVibid": "22420001399915",
        "fullName": "Пимашков Петр Иванович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:22420001400099",
        "candidateVibid": "22420001400099",
        "fullName": "Подоляк Наталия Михайловна",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001387092",
        "candidateVibid": "22420001387092",
        "fullName": "Серебряков Иван Александрович",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001397298",
        "candidateVibid": "22420001397298",
        "fullName": "Урдаев Анатолий Юрьевич",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001321249",
        "candidateVibid": "22420001321249",
        "fullName": "Юрков Алексей Николаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/krasnoyarsk?action=show&root=1000073&tvd=100100067795927&vrn=100100067795849&region=24&global=null&sub_region=24&prver=0&pronetvd=null&vibid=100100067795927&type=463",
        "sha256": "7106a01f5de214bba49cfb2ae959abd9db8ac4bcd565200483bbae29d0a1aa39",
        "retrievedAt": "2026-08-28T07:42:11.631952+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/krasnoyarsk?action=show&root=1000073&tvd=100100067795927&vrn=100100067795849&region=24&global=null&sub_region=24&prver=0&pronetvd=null&vibid=100100067795927&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 75957,
        "summedTikWinnerVoteTotal": 75957
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 56,
    "oikTvd": "100100067795928",
    "oikName": "Красноярский край – Дивногорский",
    "regionCode": "24",
    "regionTvd": "100100067795925",
    "regionName": "Красноярский край",
    "winnerCandidateVibid": "22420001399802",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:22420001401198",
        "candidateVibid": "22420001401198",
        "fullName": "Ербягин Сергей Александрович",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001395025",
        "candidateVibid": "22420001395025",
        "fullName": "Золотухин Максим Анатольевич",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001399802",
        "candidateVibid": "22420001399802",
        "fullName": "Зубарев Виктор Владиславович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:22420001401772",
        "candidateVibid": "22420001401772",
        "fullName": "Иванова Ирина Геннадьевна",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001395182",
        "candidateVibid": "22420001395182",
        "fullName": "Носов Дмитрий Юрьевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001398689",
        "candidateVibid": "22420001398689",
        "fullName": "Питерский Ярослав Михайлович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001400204",
        "candidateVibid": "22420001400204",
        "fullName": "Ромашечкина Ирина Васильевна",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "выбывший (после регистрации) кандидат",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001387128",
        "candidateVibid": "22420001387128",
        "fullName": "Семигин Геннадий Юрьевич",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001258133",
        "candidateVibid": "22420001258133",
        "fullName": "Ульских Роман Николаевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001401210",
        "candidateVibid": "22420001401210",
        "fullName": "Ульянова Валентина Петровна",
        "nominatingEntity": "Политическая партия \"Гражданская Платформа\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/krasnoyarsk?action=show&root=1000074&tvd=100100067795928&vrn=100100067795849&region=24&global=null&sub_region=24&prver=0&pronetvd=null&vibid=100100067795928&type=463",
        "sha256": "f58f1a8d0d75fe52861e03be5dba64a4edf14f4386761501edb35bb04f742704",
        "retrievedAt": "2026-08-28T07:42:11.821544+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/krasnoyarsk?action=show&root=1000074&tvd=100100067795928&vrn=100100067795849&region=24&global=null&sub_region=24&prver=0&pronetvd=null&vibid=100100067795928&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 90661,
        "summedTikWinnerVoteTotal": 90661
      }
    }
  },
  {
    "election": "2016-duma",
    "districtNumber": 57,
    "oikTvd": "100100067795929",
    "oikName": "Красноярский край – Енисейский",
    "regionCode": "24",
    "regionTvd": "100100067795925",
    "regionName": "Красноярский край",
    "winnerCandidateVibid": "22420001400155",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:22420001399873",
        "candidateVibid": "22420001399873",
        "fullName": "Дьяков Александр Александрович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001400047",
        "candidateVibid": "22420001400047",
        "fullName": "Карданец Артем Викторович",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001400155",
        "candidateVibid": "22420001400155",
        "fullName": "Кармазина Раиса Васильевна",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:22420001397838",
        "candidateVibid": "22420001397838",
        "fullName": "Лановая Ольга Викторовна",
        "nominatingEntity": "Политическая партия \"Гражданская Платформа\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001395036",
        "candidateVibid": "22420001395036",
        "fullName": "Лымпио Александр Сергеевич",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001258144",
        "candidateVibid": "22420001258144",
        "fullName": "Натаров Сергей Васильевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001400275",
        "candidateVibid": "22420001400275",
        "fullName": "Полежаев Петр Иванович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001387151",
        "candidateVibid": "22420001387151",
        "fullName": "Рыкунова Татьяна Евгеньевна",
        "nominatingEntity": "Политическая партия \"ПАТРИОТЫ РОССИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:22420001389166",
        "candidateVibid": "22420001389166",
        "fullName": "Селезнев Андрей Валерьевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/krasnoyarsk?action=show&root=1000075&tvd=100100067795929&vrn=100100067795849&region=24&global=null&sub_region=24&prver=0&pronetvd=null&vibid=100100067795929&type=463",
        "sha256": "c21177d4d951741a371685b81fcc844806f2a1e833f4e0fa7272556228331d33",
        "retrievedAt": "2026-08-28T07:42:11.970059+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/krasnoyarsk?action=show&root=1000075&tvd=100100067795929&vrn=100100067795849&region=24&global=null&sub_region=24&prver=0&pronetvd=null&vibid=100100067795929&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 91725,
        "summedTikWinnerVoteTotal": 91725
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
