// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2016_districts_region_6 = [
  {
    "election": "2016-duma",
    "districtNumber": 13,
    "oikTvd": "100100067795873",
    "oikName": "Республика Ингушетия – Ингушский",
    "regionCode": "6",
    "regionTvd": "100100067795872",
    "regionName": "Республика Ингушетия",
    "winnerCandidateVibid": "2062000284089",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2062000284511",
        "candidateVibid": "2062000284511",
        "fullName": "Богатырев Ильяс Сулейманович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2062000284074",
        "candidateVibid": "2062000284074",
        "fullName": "Борщев Валерий Васильевич",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2062000284053",
        "candidateVibid": "2062000284053",
        "fullName": "Гадиев Ислам Геланиевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2062000284031",
        "candidateVibid": "2062000284031",
        "fullName": "Гусейнов Мухамедали Сардарович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2062000284548",
        "candidateVibid": "2062000284548",
        "fullName": "Дзауров Магамет Хасанович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2062000275440",
        "candidateVibid": "2062000275440",
        "fullName": "Евлоев Борис Борисович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2062000281074",
        "candidateVibid": "2062000281074",
        "fullName": "Келигов Башир Муссаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2062000280634",
        "candidateVibid": "2062000280634",
        "fullName": "Келигова Лейла Магомедовна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2062000284042",
        "candidateVibid": "2062000284042",
        "fullName": "Мартазанов Абдулмажит Кадирович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2062000284089",
        "candidateVibid": "2062000284089",
        "fullName": "Харсиев Алихан Анатольевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "voteKey": "gas:candidate-vibid:2062000284101",
        "candidateVibid": "2062000284101",
        "fullName": "Чемхильгов Казбек Баширович",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/ingush?action=show&root=1000019&tvd=100100067795873&vrn=100100067795849&region=6&global=null&sub_region=6&prver=0&pronetvd=null&vibid=100100067795873&type=463",
        "sha256": "d2eedca318261eacee648c8ad834c838fd511a362e0891ac1339086ee8756e67",
        "retrievedAt": "2026-08-28T07:42:01.934681+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/ingush?action=show&root=1000019&tvd=100100067795873&vrn=100100067795849&region=6&global=null&sub_region=6&prver=0&pronetvd=null&vibid=100100067795873&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 125921,
        "summedTikWinnerVoteTotal": 125921
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
