// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2016_districts_region_28 = [
  {
    "election": "2016-duma",
    "districtNumber": 71,
    "oikTvd": "100100067795943",
    "oikName": "Амурская область – Амурский",
    "regionCode": "28",
    "regionTvd": "100100067795942",
    "regionName": "Амурская область",
    "winnerCandidateVibid": "2282000785455",
    "candidates": [
      {
        "voteKey": "gas:candidate-vibid:2282000785455",
        "candidateVibid": "2282000785455",
        "fullName": "Абрамов Иван Николаевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": true,
        "registryIsElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2282000852222",
        "candidateVibid": "2282000852222",
        "fullName": "Барило Роман Владимирович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2282000816690",
        "candidateVibid": "2282000816690",
        "fullName": "Волков Евгений Иванович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2282000816730",
        "candidateVibid": "2282000816730",
        "fullName": "Зимин Кирилл Вячеславович",
        "nominatingEntity": "Политическая партия СПРАВЕДЛИВАЯ РОССИЯ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2282000852273",
        "candidateVibid": "2282000852273",
        "fullName": "Калинина Наталья Владимировна",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2282000816665",
        "candidateVibid": "2282000816665",
        "fullName": "Кобызов Роман Александрович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2282000778160",
        "candidateVibid": "2282000778160",
        "fullName": "Лунёв Анатолий Борисович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2282000809028",
        "candidateVibid": "2282000809028",
        "fullName": "Мигуля Александр Анатольевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2282000779025",
        "candidateVibid": "2282000779025",
        "fullName": "Орлова Жаккелина Эдуардовна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "voteKey": "gas:candidate-vibid:2282000852262",
        "candidateVibid": "2282000852262",
        "fullName": "Паршинков Валерий Борисович",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"Зеленые\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "resultIdentityAnomalies": [],
    "obfuscatedWinnerLabelAnomalies": [],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "sha256": "e79a29135ad9d9ba03906abbdb09016d96ff5e41bf1af39ba2d4b1efb7062282",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T07:41:58.689415+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/izbirkom?action=show&root=0&tvd=100100067795854&vrn=100100067795849&region=0&global=&sub_region=0&prver=0&pronetvd=null&vibid=100100067795849&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://old.izbirkom.ru/region/region/amur?action=show&root=1000089&tvd=100100067795943&vrn=100100067795849&region=28&global=null&sub_region=28&prver=0&pronetvd=null&vibid=100100067795943&type=463",
        "sha256": "6e4534aeb845980bbef73ea996fa55ea726e25727dc5aabf8ae41893754210a2",
        "retrievedAt": "2026-08-28T07:42:14.501305+00:00",
        "finalUrl": "http://old.izbirkom.ru/region/region/amur?action=show&root=1000089&tvd=100100067795943&vrn=100100067795849&region=28&global=null&sub_region=28&prver=0&pronetvd=null&vibid=100100067795943&type=463",
        "provenance": "live-official",
        "sourceReportType": 463,
        "winnerDerivation": "summed-official-tik-results-validated-against-oik-total",
        "oikUniqueHighestVoteTotal": 123762,
        "summedTikWinnerVoteTotal": 123762
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
