// This file is auto-generated by proper-data/crawler/generate_historical_typescript.py.
// Do not edit it manually.

import type { UikTikRelation } from "../protocol/types";

export const president_2008_uik_to_tik_region_9 = [
  {
    "uikNumber": 1,
    "uikTvd": "409401090357",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 2,
    "uikTvd": "409401090358",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 3,
    "uikTvd": "409401090359",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 4,
    "uikTvd": "409401090360",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 5,
    "uikTvd": "409401090361",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 6,
    "uikTvd": "409401090362",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 7,
    "uikTvd": "409401090363",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 8,
    "uikTvd": "409401090364",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 9,
    "uikTvd": "409401090365",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 10,
    "uikTvd": "409401090366",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 11,
    "uikTvd": "409401090367",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 12,
    "uikTvd": "409401090368",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 13,
    "uikTvd": "409401090369",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 14,
    "uikTvd": "409401090370",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 15,
    "uikTvd": "409401090371",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 16,
    "uikTvd": "409401090372",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 17,
    "uikTvd": "409401090373",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 18,
    "uikTvd": "409401090374",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 19,
    "uikTvd": "409401090375",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 20,
    "uikTvd": "409401090376",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 21,
    "uikTvd": "409401090377",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 22,
    "uikTvd": "409401090378",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 23,
    "uikTvd": "409401090379",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 24,
    "uikTvd": "409401090380",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 25,
    "uikTvd": "409401090381",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 26,
    "uikTvd": "409401090382",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 27,
    "uikTvd": "409401090383",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 28,
    "uikTvd": "409401090384",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 29,
    "uikTvd": "409401090385",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 30,
    "uikTvd": "409401090386",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 31,
    "uikTvd": "409401090387",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 32,
    "uikTvd": "409401090388",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 33,
    "uikTvd": "409401090389",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 34,
    "uikTvd": "409401090390",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 35,
    "uikTvd": "409401090391",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 36,
    "uikTvd": "409401090392",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 37,
    "uikTvd": "409401090393",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 38,
    "uikTvd": "409401090394",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 39,
    "uikTvd": "409401090395",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 40,
    "uikTvd": "409401090396",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 41,
    "uikTvd": "409401090397",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 42,
    "uikTvd": "409401090398",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 43,
    "uikTvd": "409401090399",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 44,
    "uikTvd": "409401090400",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 45,
    "uikTvd": "409401090401",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 46,
    "uikTvd": "409401090402",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 47,
    "uikTvd": "409401090403",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 48,
    "uikTvd": "409401090404",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 49,
    "uikTvd": "409401090405",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 50,
    "uikTvd": "409401090406",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 51,
    "uikTvd": "409401090407",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 52,
    "uikTvd": "409401090408",
    "tikTvd": "2092000129844",
    "tikName": "Черкесская городская"
  },
  {
    "uikNumber": 53,
    "uikTvd": "409400485516",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 54,
    "uikTvd": "409400485518",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 55,
    "uikTvd": "409400485519",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 56,
    "uikTvd": "409400485520",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 57,
    "uikTvd": "409400485521",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 58,
    "uikTvd": "409400485522",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 59,
    "uikTvd": "409400485523",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 60,
    "uikTvd": "409400485524",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 61,
    "uikTvd": "409400485525",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 62,
    "uikTvd": "409400485526",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 63,
    "uikTvd": "409400485527",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 64,
    "uikTvd": "409400485528",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 65,
    "uikTvd": "409400485529",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 66,
    "uikTvd": "409400485530",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 67,
    "uikTvd": "409400485531",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 68,
    "uikTvd": "409400485532",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 69,
    "uikTvd": "409400485533",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 70,
    "uikTvd": "409400485534",
    "tikTvd": "2092000129851",
    "tikName": "Карачаевская городская"
  },
  {
    "uikNumber": 71,
    "uikTvd": "4094001118828",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 72,
    "uikTvd": "4094001118829",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 73,
    "uikTvd": "4094001118830",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 74,
    "uikTvd": "4094001118831",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 75,
    "uikTvd": "4094001118832",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 76,
    "uikTvd": "4094001118833",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 77,
    "uikTvd": "4094001118834",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 78,
    "uikTvd": "4094001118835",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 79,
    "uikTvd": "4094001118836",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 80,
    "uikTvd": "4094001118837",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 81,
    "uikTvd": "4094001118838",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 82,
    "uikTvd": "4094001118839",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 83,
    "uikTvd": "4094001118840",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 84,
    "uikTvd": "4094001118841",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 85,
    "uikTvd": "4094001118842",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 86,
    "uikTvd": "4094001118843",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 87,
    "uikTvd": "4094001118844",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 88,
    "uikTvd": "4094001118845",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 89,
    "uikTvd": "4094001118846",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 90,
    "uikTvd": "4094001118847",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 91,
    "uikTvd": "4094001118848",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 92,
    "uikTvd": "4094001118849",
    "tikTvd": "2092000129852",
    "tikName": "Адыге-Хабльская "
  },
  {
    "uikNumber": 93,
    "uikTvd": "4094002123228",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 94,
    "uikTvd": "4094002123229",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 95,
    "uikTvd": "4094002123230",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 96,
    "uikTvd": "4094002123231",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 97,
    "uikTvd": "4094002123232",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 98,
    "uikTvd": "4094002123233",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 99,
    "uikTvd": "4094002123234",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 100,
    "uikTvd": "4094002123235",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 101,
    "uikTvd": "4094002123236",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 102,
    "uikTvd": "4094002123237",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 103,
    "uikTvd": "4094002123238",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 104,
    "uikTvd": "4094002123239",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 105,
    "uikTvd": "4094002123240",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 106,
    "uikTvd": "4094002123241",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 107,
    "uikTvd": "4094002123242",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 108,
    "uikTvd": "4094002123243",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 109,
    "uikTvd": "4094002123244",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 110,
    "uikTvd": "4094002123245",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 111,
    "uikTvd": "4094002123246",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 112,
    "uikTvd": "4094002123247",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 113,
    "uikTvd": "4094002123248",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 114,
    "uikTvd": "4094002123249",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 115,
    "uikTvd": "4094002123250",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 116,
    "uikTvd": "4094002123251",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 117,
    "uikTvd": "4094002123252",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 118,
    "uikTvd": "4094002123253",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 119,
    "uikTvd": "4094002123254",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 120,
    "uikTvd": "4094002123255",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 121,
    "uikTvd": "4094002123256",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 122,
    "uikTvd": "4094002123257",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 123,
    "uikTvd": "4094002123258",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 124,
    "uikTvd": "4094002123259",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 125,
    "uikTvd": "4094002123260",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 126,
    "uikTvd": "4094002123261",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 127,
    "uikTvd": "4094002123262",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 128,
    "uikTvd": "4094002123263",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 129,
    "uikTvd": "4094002123264",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 130,
    "uikTvd": "4094002123273",
    "tikTvd": "2092000129849",
    "tikName": "Зеленчукская"
  },
  {
    "uikNumber": 131,
    "uikTvd": "4094003118571",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 132,
    "uikTvd": "4094003118572",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 133,
    "uikTvd": "4094003118573",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 134,
    "uikTvd": "4094003118574",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 135,
    "uikTvd": "4094003118575",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 136,
    "uikTvd": "4094003118576",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 137,
    "uikTvd": "4094003118577",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 138,
    "uikTvd": "4094003118578",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 139,
    "uikTvd": "4094003118579",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 140,
    "uikTvd": "4094003118580",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 141,
    "uikTvd": "4094003118581",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 142,
    "uikTvd": "4094003118582",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 143,
    "uikTvd": "4094003118583",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 144,
    "uikTvd": "4094003118584",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 145,
    "uikTvd": "4094003118585",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 146,
    "uikTvd": "4094003118586",
    "tikTvd": "2092000129850",
    "tikName": "Карачаевская"
  },
  {
    "uikNumber": 147,
    "uikTvd": "4094005110477",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 148,
    "uikTvd": "4094005110478",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 149,
    "uikTvd": "4094005110479",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 150,
    "uikTvd": "4094005110480",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 151,
    "uikTvd": "4094005110481",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 152,
    "uikTvd": "4094005110482",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 153,
    "uikTvd": "4094005110483",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 154,
    "uikTvd": "4094005110484",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 155,
    "uikTvd": "4094005110485",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 156,
    "uikTvd": "4094005110486",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 157,
    "uikTvd": "4094005110487",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 158,
    "uikTvd": "4094005110488",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 159,
    "uikTvd": "4094005110489",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 160,
    "uikTvd": "4094005110490",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 161,
    "uikTvd": "4094005110491",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 162,
    "uikTvd": "4094005110492",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 163,
    "uikTvd": "4094005110493",
    "tikTvd": "2092000129848",
    "tikName": "Малокарачаевская"
  },
  {
    "uikNumber": 164,
    "uikTvd": "4094006127896",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 165,
    "uikTvd": "4094006127897",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 166,
    "uikTvd": "4094006127898",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 167,
    "uikTvd": "4094006127899",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 168,
    "uikTvd": "4094006127900",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 169,
    "uikTvd": "4094006127901",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 170,
    "uikTvd": "4094006127902",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 171,
    "uikTvd": "4094006127903",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 172,
    "uikTvd": "4094006127904",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 173,
    "uikTvd": "4094006127905",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 174,
    "uikTvd": "4094006127906",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 175,
    "uikTvd": "4094006127907",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 176,
    "uikTvd": "4094006127908",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 177,
    "uikTvd": "4094006127909",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 178,
    "uikTvd": "4094006127910",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 179,
    "uikTvd": "4094006127911",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 180,
    "uikTvd": "4094006127912",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 181,
    "uikTvd": "4094006127913",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 182,
    "uikTvd": "4094006127914",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 183,
    "uikTvd": "4094006127915",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 184,
    "uikTvd": "4094006127916",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 185,
    "uikTvd": "4094006127917",
    "tikTvd": "2092000129847",
    "tikName": "Прикубанская"
  },
  {
    "uikNumber": 186,
    "uikTvd": "9099007132734",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 187,
    "uikTvd": "9099007132735",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 188,
    "uikTvd": "9099007132736",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 189,
    "uikTvd": "9099007132737",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 190,
    "uikTvd": "9099007132738",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 191,
    "uikTvd": "9099007132739",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 192,
    "uikTvd": "9099007132740",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 193,
    "uikTvd": "9099007132741",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 194,
    "uikTvd": "9099007132742",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 195,
    "uikTvd": "9099007132743",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 196,
    "uikTvd": "9099007132744",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 197,
    "uikTvd": "9099007132745",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 198,
    "uikTvd": "9099007132746",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 199,
    "uikTvd": "9099007132747",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 200,
    "uikTvd": "9099007132748",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 201,
    "uikTvd": "9099007132749",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 202,
    "uikTvd": "9099007132750",
    "tikTvd": "2092000129846",
    "tikName": "Урупская"
  },
  {
    "uikNumber": 203,
    "uikTvd": "4094008110482",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 204,
    "uikTvd": "4094008110484",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 205,
    "uikTvd": "4094008110486",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 206,
    "uikTvd": "4094008110487",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 207,
    "uikTvd": "4094008110488",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 208,
    "uikTvd": "4094008110489",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 209,
    "uikTvd": "4094008110490",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 210,
    "uikTvd": "4094008110491",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 211,
    "uikTvd": "4094008110492",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 212,
    "uikTvd": "4094008110493",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 213,
    "uikTvd": "4094008110494",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 214,
    "uikTvd": "4094008110495",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 215,
    "uikTvd": "4094008110496",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 216,
    "uikTvd": "4094008110497",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 217,
    "uikTvd": "4094008110498",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 218,
    "uikTvd": "4094008110499",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 219,
    "uikTvd": "4094008110500",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 220,
    "uikTvd": "4094008110501",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 221,
    "uikTvd": "4094008110502",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 222,
    "uikTvd": "4094008110503",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 223,
    "uikTvd": "4094008110504",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 224,
    "uikTvd": "4094008110505",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 225,
    "uikTvd": "4094008110506",
    "tikTvd": "2092000129845",
    "tikName": "Усть-Джегутинская"
  },
  {
    "uikNumber": 226,
    "uikTvd": "4094009115311",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 227,
    "uikTvd": "4094009115312",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 228,
    "uikTvd": "4094009115298",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 229,
    "uikTvd": "4094009115299",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 230,
    "uikTvd": "4094009115300",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 231,
    "uikTvd": "4094009115301",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 232,
    "uikTvd": "4094009115302",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 233,
    "uikTvd": "4094009115303",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 234,
    "uikTvd": "4094009115304",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 235,
    "uikTvd": "4094009115305",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 236,
    "uikTvd": "4094009115306",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 237,
    "uikTvd": "4094009115307",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 238,
    "uikTvd": "4094009115308",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 239,
    "uikTvd": "4094009115309",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 240,
    "uikTvd": "4094009115310",
    "tikTvd": "2092000129843",
    "tikName": "Хабезская"
  },
  {
    "uikNumber": 241,
    "uikTvd": "409401171526",
    "tikTvd": "2092000129853",
    "tikName": "Абазинская"
  },
  {
    "uikNumber": 242,
    "uikTvd": "409401171527",
    "tikTvd": "2092000129853",
    "tikName": "Абазинская"
  },
  {
    "uikNumber": 243,
    "uikTvd": "409401171528",
    "tikTvd": "2092000129853",
    "tikName": "Абазинская"
  },
  {
    "uikNumber": 244,
    "uikTvd": "409401171529",
    "tikTvd": "2092000129853",
    "tikName": "Абазинская"
  },
  {
    "uikNumber": 245,
    "uikTvd": "409401171530",
    "tikTvd": "2092000129853",
    "tikName": "Абазинская"
  },
  {
    "uikNumber": 246,
    "uikTvd": "409401171531",
    "tikTvd": "2092000129853",
    "tikName": "Абазинская"
  },
  {
    "uikNumber": 247,
    "uikTvd": "409401171532",
    "tikTvd": "2092000129853",
    "tikName": "Абазинская"
  }
] satisfies readonly UikTikRelation[];
