// This file is auto-generated by proper-data/crawler/generate_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2021_districts_region_55 = [
  {
    "election": "2021-duma",
    "districtNumber": 139,
    "oikTvd": "100100225883620",
    "oikName": "Омская область – Омский",
    "regionCode": "55",
    "regionTvd": "100100225883619",
    "regionName": "Омская область",
    "winnerCandidateVibid": "25520001566104",
    "candidates": [
      {
        "candidateVibid": "25520001566104",
        "fullName": "Алехин Андрей Анатольевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "candidateVibid": "25520001568280",
        "fullName": "Байков Алексей Анатольевич",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001565912",
        "fullName": "Берендеев Антон Юрьевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001567832",
        "fullName": "Бонковский Степан Степанович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001567791",
        "fullName": "Жарков Виктор Александрович",
        "nominatingEntity": "Социалистическая политическая партия \"СПРАВЕДЛИВАЯ РОССИЯ – ПАТРИОТЫ – ЗА ПРАВДУ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001575593",
        "fullName": "Павлов Геннадий Александрович",
        "nominatingEntity": "Политическая партия \"Российская партия пенсионеров за социальную справедливость\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001575556",
        "fullName": "Тузова Наталья Александровна",
        "nominatingEntity": "Политическая партия \"НОВЫЕ ЛЮДИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001575513",
        "fullName": "Шнейдер Татьяна Николаевна",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000183&tvd=100100225883620&vrn=100100225883172&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "sha256": "e59ce4d70a0985f972dd997b655f8332fbb87e8323dacacccf8efce37793dcda",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T06:02:13.680456+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000183&tvd=100100225883620&vrn=100100225883172&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "sha256": "b8744c5796c6d5ee6ca05421a0d66aeb4f0098271a4039aea290c60af29ea20e",
        "resolution": "61/467-8",
        "resolutionDate": "2021-09-24",
        "retrievedAt": "2026-08-28T06:35:44.830969+00:00",
        "finalUrl": "https://web.archive.org/web/20210926045732id_/http://www.cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "provenance": "wayback"
      }
    }
  },
  {
    "election": "2021-duma",
    "districtNumber": 140,
    "oikTvd": "100100225883621",
    "oikName": "Омская область – Москаленский",
    "regionCode": "55",
    "regionTvd": "100100225883619",
    "regionName": "Омская область",
    "winnerCandidateVibid": "25520001566153",
    "candidates": [
      {
        "candidateVibid": "25520001568294",
        "fullName": "Андрушко Светлана Васильевна",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001565923",
        "fullName": "Атаманиченко Кирилл Игоревич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001568723",
        "fullName": "Бирюков Николай Сергеевич",
        "nominatingEntity": "Политическая партия \"НОВЫЕ ЛЮДИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001575622",
        "fullName": "Дроботенко Иосиф Иосифович",
        "nominatingEntity": "Политическая партия \"Российская партия пенсионеров за социальную справедливость\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001566748",
        "fullName": "Мандрыгин Кирилл Владимирович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001571059",
        "fullName": "Перевальский Дмитрий Александрович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001566153",
        "fullName": "Смолин Олег Николаевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      }
    ],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000184&tvd=100100225883621&vrn=100100225883172&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "sha256": "56978a2db37d45fec6730dab8b01f0c05eb0c9843cd702b8ffbbac1ae996ca5e",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T06:02:13.792818+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000184&tvd=100100225883621&vrn=100100225883172&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "sha256": "b8744c5796c6d5ee6ca05421a0d66aeb4f0098271a4039aea290c60af29ea20e",
        "resolution": "61/467-8",
        "resolutionDate": "2021-09-24",
        "retrievedAt": "2026-08-28T06:35:44.830969+00:00",
        "finalUrl": "https://web.archive.org/web/20210926045732id_/http://www.cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "provenance": "wayback"
      }
    }
  },
  {
    "election": "2021-duma",
    "districtNumber": 141,
    "oikTvd": "100100225883622",
    "oikName": "Омская область – Любинский",
    "regionCode": "55",
    "regionTvd": "100100225883619",
    "regionName": "Омская область",
    "winnerCandidateVibid": "25520001566604",
    "candidates": [
      {
        "candidateVibid": "25520001575727",
        "fullName": "Добаш Ольга Владимировна",
        "nominatingEntity": "Политическая партия \"Российская партия пенсионеров за социальную справедливость\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001568305",
        "fullName": "Казанин Владимир Борисович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001568341",
        "fullName": "Лифантьев Владимир Валерьевич",
        "nominatingEntity": "Социалистическая политическая партия \"СПРАВЕДЛИВАЯ РОССИЯ – ПАТРИОТЫ – ЗА ПРАВДУ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001565934",
        "fullName": "Макаленко Максим Игоревич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001575976",
        "fullName": "Подворный Евгений Валерьевич",
        "nominatingEntity": "Политическая партия \"НОВЫЕ ЛЮДИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001566124",
        "fullName": "Ткачев Константин Германович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "25520001566604",
        "fullName": "Фадина Оксана Николаевна",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      }
    ],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000185&tvd=100100225883622&vrn=100100225883172&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "sha256": "a555e5fa74076e9c732cece6e9bac92a1d73fbac0faa42433293df60399111b3",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T06:02:14.180502+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/omsk?action=show&root=1000185&tvd=100100225883622&vrn=100100225883172&region=55&global=null&sub_region=55&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "sha256": "b8744c5796c6d5ee6ca05421a0d66aeb4f0098271a4039aea290c60af29ea20e",
        "resolution": "61/467-8",
        "resolutionDate": "2021-09-24",
        "retrievedAt": "2026-08-28T06:35:44.830969+00:00",
        "finalUrl": "https://web.archive.org/web/20210926045732id_/http://www.cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "provenance": "wayback"
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
