// This file is auto-generated by proper-data/crawler/generate_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2021_districts_region_83 = [
  {
    "election": "2021-duma",
    "districtNumber": 221,
    "oikTvd": "100100225883724",
    "oikName": "Ненецкий автономный округ – Ненецкий",
    "regionCode": "83",
    "regionTvd": "100100225883723",
    "regionName": "Ненецкий автономный округ",
    "winnerCandidateVibid": "2832000392217",
    "candidates": [
      {
        "candidateVibid": "2832000392856",
        "fullName": "Брескаленко Олег Иванович",
        "nominatingEntity": "Социалистическая политическая партия \"СПРАВЕДЛИВАЯ РОССИЯ – ПАТРИОТЫ – ЗА ПРАВДУ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2832000392217",
        "fullName": "Коткин Сергей Николаевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "candidateVibid": "2832000392378",
        "fullName": "Миловский Николай Леонидович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2832000392700",
        "fullName": "Никитин Дмитрий Дмитриевич",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"ЗЕЛЁНЫЕ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2832000392109",
        "fullName": "Райн Михаил Викторович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2832000392997",
        "fullName": "Смыченков Андрей Владимирович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/nenetsk?action=show&root=1000287&tvd=100100225883724&vrn=100100225883172&region=83&global=null&sub_region=83&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "sha256": "0a0523a5e00d0cd7de870cfd468d0a9f7ae5d66f4879ac80b6652c046c01819a",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T06:02:32.236605+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/nenetsk?action=show&root=1000287&tvd=100100225883724&vrn=100100225883172&region=83&global=null&sub_region=83&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "sha256": "b8744c5796c6d5ee6ca05421a0d66aeb4f0098271a4039aea290c60af29ea20e",
        "resolution": "61/467-8",
        "resolutionDate": "2021-09-24",
        "retrievedAt": "2026-08-28T06:35:44.830969+00:00",
        "finalUrl": "https://web.archive.org/web/20210926045732id_/http://www.cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "provenance": "wayback"
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
