// This file is auto-generated by proper-data/crawler/generate_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2021_districts_region_8 = [
  {
    "election": "2021-duma",
    "districtNumber": 15,
    "oikTvd": "100100225883420",
    "oikName": "Республика Калмыкия – Калмыцкий",
    "regionCode": "8",
    "regionTvd": "100100225883419",
    "regionName": "Республика Калмыкия",
    "winnerCandidateVibid": "2082000615419",
    "candidates": [
      {
        "candidateVibid": "2082000614531",
        "fullName": "Бадмаев Валерий Антонович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "candidateVibid": "2082000616218",
        "fullName": "Бамбаев Владимир Харцхаевич",
        "nominatingEntity": "Политическая партия РОССИЙСКАЯ ПАРТИЯ СВОБОДЫ И СПРАВЕДЛИВОСТИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2082000615419",
        "fullName": "Башанкаев Бадма Николаевич",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "candidateVibid": "2082000616241",
        "fullName": "Боваев Санал Оляевич",
        "nominatingEntity": "Политическая партия \"Российская партия пенсионеров за социальную справедливость\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2082000615075",
        "fullName": "Бурнинов Дмитрий Борисович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "candidateVibid": "2082000614631",
        "fullName": "Вышкварок Петр Петрович",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2082000616574",
        "fullName": "Котенова Елена Горяевна",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2082000614894",
        "fullName": "Лиджиев Анатолий Владимирович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "",
        "isElected": false
      },
      {
        "candidateVibid": "2082000615204",
        "fullName": "Манжикова Наталья Сергеевна",
        "nominatingEntity": "Социалистическая политическая партия \"СПРАВЕДЛИВАЯ РОССИЯ – ПАТРИОТЫ – ЗА ПРАВДУ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2082000616705",
        "fullName": "Марилов Хонгор Анатольевич",
        "nominatingEntity": "Политическая партия \"Гражданская Платформа\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2082000615727",
        "fullName": "Очир-Горяев Цэрен Николаевич",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2082000615546",
        "fullName": "Убушиев Санал Валерьевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2082000616267",
        "fullName": "Чиджиев Андрей Улюмджиевич",
        "nominatingEntity": "Политическая партия \"НОВЫЕ ЛЮДИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "2082000615005",
        "fullName": "Эрдниева Валентина Владимировна",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      }
    ],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/kalmyk?action=show&root=1000023&tvd=100100225883420&vrn=100100225883172&region=8&global=null&sub_region=8&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "sha256": "d844efcec8833746a0a343b3e081e96beea844bd7388c41e730acac76f914103",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T06:01:45.880098+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/kalmyk?action=show&root=1000023&tvd=100100225883420&vrn=100100225883172&region=8&global=null&sub_region=8&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "sha256": "b8744c5796c6d5ee6ca05421a0d66aeb4f0098271a4039aea290c60af29ea20e",
        "resolution": "61/467-8",
        "resolutionDate": "2021-09-24",
        "retrievedAt": "2026-08-28T06:35:44.830969+00:00",
        "finalUrl": "https://web.archive.org/web/20210926045732id_/http://www.cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "provenance": "wayback"
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
