// This file is auto-generated by proper-data/crawler/generate_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2021_districts_region_35 = [
  {
    "election": "2021-duma",
    "districtNumber": 85,
    "oikTvd": "100100225883507",
    "oikName": "Вологодская область – Вологодский",
    "regionCode": "35",
    "regionTvd": "100100225883506",
    "regionName": "Вологодская область",
    "winnerCandidateVibid": "23520001454075",
    "candidates": [
      {
        "candidateVibid": "23520001452774",
        "fullName": "Анферьев Илья Михайлович",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001454075",
        "fullName": "Артамонова Валентина Николаевна",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "candidateVibid": "23520001460070",
        "fullName": "Болотов Александр Леонидович",
        "nominatingEntity": "Политическая партия \"Российская партия пенсионеров за социальную справедливость\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001445036",
        "fullName": "Гримов Антон Юрьевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001458533",
        "fullName": "Доможирова Ольга Евгеньевна",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001456533",
        "fullName": "Ершов Олег Александрович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001454064",
        "fullName": "Леухин Виктор Львович",
        "nominatingEntity": "Социалистическая политическая партия \"СПРАВЕДЛИВАЯ РОССИЯ – ПАТРИОТЫ – ЗА ПРАВДУ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001458896",
        "fullName": "Паутов Андрей Викторович",
        "nominatingEntity": "Политическая партия \"НОВЫЕ ЛЮДИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/vologod?action=show&root=1000110&tvd=100100225883507&vrn=100100225883172&region=35&global=null&sub_region=35&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "sha256": "04cda4e54d47832548dd9b8e950dcf5fe92d85b565d442e02ed191c321884fbc",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T06:02:01.602253+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/vologod?action=show&root=1000110&tvd=100100225883507&vrn=100100225883172&region=35&global=null&sub_region=35&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "sha256": "b8744c5796c6d5ee6ca05421a0d66aeb4f0098271a4039aea290c60af29ea20e",
        "resolution": "61/467-8",
        "resolutionDate": "2021-09-24",
        "retrievedAt": "2026-08-28T06:35:44.830969+00:00",
        "finalUrl": "https://web.archive.org/web/20210926045732id_/http://www.cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "provenance": "wayback"
      }
    }
  },
  {
    "election": "2021-duma",
    "districtNumber": 86,
    "oikTvd": "100100225883508",
    "oikName": "Вологодская область – Череповецкий",
    "regionCode": "35",
    "regionTvd": "100100225883506",
    "regionName": "Вологодская область",
    "winnerCandidateVibid": "23520001452785",
    "candidates": [
      {
        "candidateVibid": "23520001415607",
        "fullName": "Асланов Руслан Седуллаевич",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "candidateVibid": "23520001455320",
        "fullName": "Вобликова Светлана Александровна",
        "nominatingEntity": "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ \"РОДИНА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001451508",
        "fullName": "Ерегин Юрий Анатольевич",
        "nominatingEntity": "Социалистическая политическая партия \"СПРАВЕДЛИВАЯ РОССИЯ – ПАТРИОТЫ – ЗА ПРАВДУ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001452785",
        "fullName": "Канаев Алексей Валерианович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "candidateVibid": "23520001460081",
        "fullName": "Катухин Игорь Васильевич",
        "nominatingEntity": "Политическая партия \"Российская партия пенсионеров за социальную справедливость\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001456544",
        "fullName": "Морозов Александр Николаевич",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001461671",
        "fullName": "Рытов Иван Геннадьевич",
        "nominatingEntity": "Политическая партия \"НОВЫЕ ЛЮДИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "23520001445008",
        "fullName": "Ширикова Ольга Станиславовна",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/vologod?action=show&root=1000111&tvd=100100225883508&vrn=100100225883172&region=35&global=null&sub_region=35&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "sha256": "ece2e1b4cb862c30d1b81866cdb0934354bb45d6e27c1f2fa88f2baccd27ddb9",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T06:02:01.923951+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/vologod?action=show&root=1000111&tvd=100100225883508&vrn=100100225883172&region=35&global=null&sub_region=35&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "sha256": "b8744c5796c6d5ee6ca05421a0d66aeb4f0098271a4039aea290c60af29ea20e",
        "resolution": "61/467-8",
        "resolutionDate": "2021-09-24",
        "retrievedAt": "2026-08-28T06:35:44.830969+00:00",
        "finalUrl": "https://web.archive.org/web/20210926045732id_/http://www.cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "provenance": "wayback"
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
