// This file is auto-generated by proper-data/crawler/generate_typescript.py.
// Do not edit it manually.

import type { SingleMemberDistrict } from "../protocol/types";

export const duma_2021_districts_region_40 = [
  {
    "election": "2021-duma",
    "districtNumber": 99,
    "oikTvd": "100100225883526",
    "oikName": "Калужская область – Калужский",
    "regionCode": "40",
    "regionTvd": "100100225883525",
    "regionName": "Калужская область",
    "winnerCandidateVibid": "24020001148050",
    "candidates": [
      {
        "candidateVibid": "24020001146290",
        "fullName": "Бычков Александр Петрович",
        "nominatingEntity": "Социалистическая политическая партия \"СПРАВЕДЛИВАЯ РОССИЯ – ПАТРИОТЫ – ЗА ПРАВДУ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001144021",
        "fullName": "Головнев Игорь Игоревич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001146894",
        "fullName": "Зубов Дмитрий Викторович",
        "nominatingEntity": "Политическая партия \"НОВЫЕ ЛЮДИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001148004",
        "fullName": "Колесникова Екатерина Владимировна",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "выбывший (после регистрации) кандидат",
        "isElected": false
      },
      {
        "candidateVibid": "24020001148050",
        "fullName": "Коробова Ольга Владимировна",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "candidateVibid": "24020001147614",
        "fullName": "Матико Михаил Михайлович",
        "nominatingEntity": "Политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001148683",
        "fullName": "Михайлов Владимир Викторович",
        "nominatingEntity": "Политическая партия \"Российская партия пенсионеров за социальную справедливость\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001148232",
        "fullName": "Рахе Дмитрий Юрьевич",
        "nominatingEntity": "Всероссийская политическая партия \"ПАРТИЯ РОСТА\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001148534",
        "fullName": "Щербаков Виктор Андреевич",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"ЗЕЛЁНЫЕ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001146529",
        "fullName": "Яшкин Николай Иванович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/kaluga?action=show&root=1000129&tvd=100100225883526&vrn=100100225883172&region=40&global=null&sub_region=40&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "sha256": "f7479658ddf28d31d1f7d047a4122401da545d5621c5f460dcee2e5497e20a97",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T06:02:04.804963+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/kaluga?action=show&root=1000129&tvd=100100225883526&vrn=100100225883172&region=40&global=null&sub_region=40&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "sha256": "b8744c5796c6d5ee6ca05421a0d66aeb4f0098271a4039aea290c60af29ea20e",
        "resolution": "61/467-8",
        "resolutionDate": "2021-09-24",
        "retrievedAt": "2026-08-28T06:35:44.830969+00:00",
        "finalUrl": "https://web.archive.org/web/20210926045732id_/http://www.cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "provenance": "wayback"
      }
    }
  },
  {
    "election": "2021-duma",
    "districtNumber": 100,
    "oikTvd": "100100225883527",
    "oikName": "Калужская область – Обнинский",
    "regionCode": "40",
    "regionTvd": "100100225883525",
    "regionName": "Калужская область",
    "winnerCandidateVibid": "24020001147963",
    "candidates": [
      {
        "candidateVibid": "24020001147150",
        "fullName": "Архитова Марина Викторовна",
        "nominatingEntity": "Политическая партия \"НОВЫЕ ЛЮДИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001148869",
        "fullName": "Ефремов Владимир Игоревич",
        "nominatingEntity": "Политическая партия \"Российская экологическая партия \"ЗЕЛЁНЫЕ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001146334",
        "fullName": "Ефремова Надежда Игоревна",
        "nominatingEntity": "Социалистическая политическая партия \"СПРАВЕДЛИВАЯ РОССИЯ – ПАТРИОТЫ – ЗА ПРАВДУ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001140509",
        "fullName": "Зыков Андрей Александрович",
        "nominatingEntity": "Самовыдвижение",
        "registrationStatus": "отказ в регистрации",
        "isElected": false
      },
      {
        "candidateVibid": "24020001146565",
        "fullName": "Иванов Николай Викторович",
        "nominatingEntity": "Политическая партия \"КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001144043",
        "fullName": "Лозенко Дмитрий Дмитриевич",
        "nominatingEntity": "Политическая партия ЛДПР – Либерально-демократическая партия России",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001147528",
        "fullName": "Лужецкий Олег Борисович",
        "nominatingEntity": "Политическая партия \"Российская объединенная демократическая партия \"ЯБЛОКО\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      },
      {
        "candidateVibid": "24020001147963",
        "fullName": "Скляр Геннадий Иванович",
        "nominatingEntity": "Всероссийская политическая партия \"ЕДИНАЯ РОССИЯ\"",
        "registrationStatus": "зарегистрирован",
        "isElected": true
      },
      {
        "candidateVibid": "24020001148709",
        "fullName": "Терехова Наталья Васильевна",
        "nominatingEntity": "Политическая партия \"Российская партия пенсионеров за социальную справедливость\"",
        "registrationStatus": "зарегистрирован",
        "isElected": false
      }
    ],
    "source": {
      "url": "http://old.izbirkom.ru/region/region/kaluga?action=show&root=1000130&tvd=100100225883527&vrn=100100225883172&region=40&global=null&sub_region=40&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "sha256": "a79dd4362412fe44dd4cad99c3d89c7b3773deabc6f75723ce76c2c3184468dd",
      "sourceReportType": 220,
      "retrievedAt": "2026-08-28T06:02:04.954404+00:00",
      "finalUrl": "http://old.izbirkom.ru/region/region/kaluga?action=show&root=1000130&tvd=100100225883527&vrn=100100225883172&region=40&global=null&sub_region=40&prver=0&pronetvd=null&vibid=100100225883172&type=220",
      "provenance": "live-official",
      "winnerSource": {
        "url": "http://cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "sha256": "b8744c5796c6d5ee6ca05421a0d66aeb4f0098271a4039aea290c60af29ea20e",
        "resolution": "61/467-8",
        "resolutionDate": "2021-09-24",
        "retrievedAt": "2026-08-28T06:35:44.830969+00:00",
        "finalUrl": "https://web.archive.org/web/20210926045732id_/http://www.cikrf.ru/upload/decree-of-cec/61-467-8-pril.docx",
        "provenance": "wayback"
      }
    }
  }
] satisfies readonly SingleMemberDistrict[];
